// Auto-generated by generate_theme.py — do not edit manually
// Last generated: 2026-07-27
var THEMES_DATA = [
  {
    tag: "AI-Revolution",
    title: "AI Revolution",
    conviction: "HIGH",
    stage: "Build-out",
    last_review: "2026-07-27",
    next_review_due: "2026-10-25",
    kpi_breach_count: "0",
    sub_trends: ["AI-Infrastructure", "Memory-Supercycle", "Optical-Interconnect", "Cloud-Acceleration", "Custom-Silicon", "Agentic-AI", "Advanced-Packaging", "Semiconductor-Equipment", "CPU-Renaissance"],
    tickers: ["MSFT", "GOOGL", "TSM", "ASML", "AMZN", "NVDA", "META", "AVGO", "LITE", "ARM", "AMD", "AAPL", "COHR", "MU", "SKHY", "SPCX"],
    content: `
## 1. Theme Story Gate

**WHAT:** AI Revolution คือการลงทุน infrastructure ครั้งใหญ่ที่สุดในประวัติศาสตร์เทคโนโลยี — Big Tech 4 รวมกัน capex ~$725B ปี 2026 (+77% YoY) — เพื่อสร้าง compute stack เต็มระบบ (GPU/CPU → memory → networking/optical → advanced packaging → equipment → cloud/monetization) ที่ตอนนี้ **ทุกชั้นพร้อมกันเป็นคอขวด** ไม่ใช่แค่ GPU เหมือนปี 2023

**WHY NOW (second-level):** Consensus รู้อยู่แล้วว่า "AI capex ใหญ่มากและกำลังโต" — นั่น price-in ไปแล้วในหุ้นหลายตัว สิ่งที่ตลาดยังไม่ price-in เต็มคือ 2 เรื่อง: (1) คอขวดกระจายไปทั้ง chain พร้อมกันจริง (memory/optical/packaging/power/equipment ตึงพร้อมกันหมด ปี 2026) ทำให้ value capture ไม่กระจุกที่ layer เดียวแบบที่ตลาดยังคิด (2) agentic AI workload มีธรรมชาติต่างจาก chatbot-era อย่างมีนัย — CPU-heavy, branchy, ทำลาย efficiency assumption ที่ทำให้ ASIC ได้เปรียบในยุค batch-inference — โมเดลส่วนใหญ่ยังตั้งสมมติฐานแบบเก่าอยู่

**IF WRONG (falsifiable):** Big Tech 4 capex รวม **หดตัว YoY จริง (ไม่ใช่แค่ growth rate ชะลอ) ติดต่อกัน 2 ไตรมาส** หรือ Anthropic/frontier-lab ARR MoM growth หลุดต่ำกว่า **20% MoM ต่อเนื่องหลายเดือนโดยมีสาเหตุจากฝั่ง demand จริง** (ไม่ใช่ throughput/supply-constraint ชั่วคราวแบบที่เห็นตอนนี้)

---

## 2. ทำไมธีมนี้ยังจริงอยู่

1. **Big Tech 4 capex 2026 ~$725B (+77% YoY)** ขึ้นจาก ~$410B ปี 2025 — ยืนยันจากผลประกอบการ Q1-Q2 2026 ทั้ง GOOGL/MSFT/AMZN/META (Review GOOG/MSFT/AWS)
2. **ASML beat-and-raise 2 รอบในปีเดียว** — FY26 revenue guide €36-40B → **€43-45B** (07-15/17); EUV shipment 2026 ปรับขึ้นเป็น 65-70 units (จากเดิม ≥60); Q3 gross margin guide 55-57% (เหนือ consensus 52%) — สัญญาณ upcycle เร่งตัว ไม่ใช่ digestion
3. **TSMC ปรับเป้า CoWoS capacity ขึ้นอีกรอบเป็น 200-220K wpm ปลายปี 2027** (จากประมาณการเดิม 170-180K, FUNDA 07-08) — demand ยังวิ่งนำ supply forecast ทุกรอบ
4. **NVDA Vera Rubin เข้า full production จริงแล้ว (07-27)** ไม่ใช่แค่ roadmap — 5-rack system (NVL72+Vera CPU+Groq 3 LPX+Spectrum-6+BlueField-4), content/GW ขยายต่อ $40bn/GW → $60-80bn/GW
5. **Server DDR contract price +60% QoQ (2Q26)** เร่งขึ้นจาก +37% ไตรมาสก่อน — memory tightness กำลังแรงขึ้น ไม่ใช่คลายตัว (UBS Memory Semis Monthly)

---

## 3. Value Chain Map

| Layer | หุ้นใน watchlist | พอร์ตถืออยู่ไหม |
|---|---|---|
| **Compute (GPU/Accelerator)** | NVDA | ✅ NVDA |
| **CPU / Custom Silicon (merchant + royalty)** | ARM, AMD, AVGO | ❌ ว่าง (ไม่มีตัวแทน) |
| **Foundry & Advanced Packaging** | TSM | ✅ TSM |
| **Semiconductor Equipment** | ASML | ❌ ว่าง |
| **Memory (HBM/DRAM)** | MU, SKHY | ❌ ว่าง |
| **Optical Interconnect** | LITE, COHR | ❌ ว่าง |
| **Cloud / Hyperscaler (compute-as-service + monetization)** | MSFT, GOOGL, AMZN, META | ✅ MSFT, AMZN, META (GOOGL ไม่ถือ) |
| **Consumer/Edge Application (peripheral ต่อธีมนี้)** | AAPL | ❌ ว่าง |
| **Frontier/Speculative Compute** | SPCX | ❌ ว่าง |

**อ่านเป็นข้อมูล ไม่ใช่คำสั่งซื้อ:** พอร์ตปัจจุบันกระจุกที่ Compute+Cloud (3/4 hyperscaler + NVDA + TSM) — ยังไม่มีตัวแทนใน CPU/Custom-Silicon, Equipment, Memory, Optical เลย แม้ layer เหล่านี้เป็นคอขวดจริงตาม §2 — เป็นข้อสังเกตเชิงโครงสร้าง (action ตัดสินที่ \`/warren watchlist\`/\`/warren\` ตามราคา+gate)

---

## 4. Quality Ranking (TQR)

*คำนวณครั้งแรก (v1) — ยังไม่มีรอบก่อนหน้าเทียบ ทุกตัว = 🆕 NEW*

| TICKER | TQR | Band | BQ | GP | RA* | Centrality | Resilience | Layer | หมายเหตุ |
|---|---|---|---|---|---|---|---|---|---|
| **[[MSFT]]** | 8.65 | 🥇 Core 🆕 | 9.5 | 8.5 | 7.5 | 8.5 | 8.5 | Cloud | Distribution moat (365/GitHub/Azure) + backlog $627B ใหญ่สุด = execution risk ต่ำสุดในธีม; Centrality สูงจาก harness multi-model lock-in ไม่ใช่ single model bet; Resilience สูงเพราะรายได้ core (Office/Windows/enterprise) ไม่ผูก AI capex |
| **[[GOOGL]]** | 8.43 | 🥈 Strong 🆕 | 9.5 | 8.5 | 6.5 | 8.5 | 8.0 | Cloud | Vertically-integrated สุด (TPU→Gemini→Antigravity→Cloud); Centrality สูงจาก TPU 8th-gen ขายนอกแล้ว; Resilience สูงเพราะ Search/YouTube ยังเป็นฐานใหญ่ไม่พึ่ง AI capex |
| **[[TSM]]** | 8.38 | 🥈 Strong 🆕 | 9.5 | 9.5 | 5.5 | 9.5 | 6.0 | Foundry/Packaging | Centrality สูงสุด (ทุกเจ้าต้องผ่าน N3/N2+CoWoS) แต่ RA* ลดจากความเสี่ยงภูมิรัฐศาสตร์ไต้หวัน + **socket-loss ใหม่** (Google TPU9 เลือก Intel EMIB-T แทน CoWoS — ครั้งแรกที่เสีย socket จริงไม่ใช่แค่ overflow); Resilience กลางเพราะมี mobile/auto SoC นอก AI |
| **[[ASML]]** | 8.25 | 🥈 Strong 🆕 | 9.5 | 8.5 | 6.5 | 9.5 | 5.5 | Equipment | EUV monopoly แท้ (ไม่มีคู่แข่งจริง) → Centrality สูงสุดเท่า TSM; RA* คุมด้วยความเสี่ยง China export control (~25-30% รายได้); Resilience กลางเพราะขายให้ผู้ผลิตชิปทุกประเภทไม่ใช่แค่ AI fab |
| **[[AMZN]]** | 8.25 | 🥈 Strong 🆕 | 9.0 | 8.5 | 6.5 | 8.0 | 8.5 | Cloud | Trainium $225B+ committed + AWS capacity-constrained; Resilience สูงสุดในกลุ่ม hyperscaler เพราะ e-commerce retail ยังเป็นสัดส่วนใหญ่ของรายได้รวม |
| **[[NVDA]]** | 8.00 | 🥈 Strong 🆕 | 9.5 | 9.5 | 6.5 | 9.5 | 2.5 | Compute | คุณภาพ/growth/centrality สูงสุดในธีม (CUDA lock-in + Vera Rubin production) — แต่ **Resilience ต่ำสุดในทุกตัว** เพราะรายได้เกือบทั้งหมดผูกกับ AI datacenter capex โดยตรง ถ้า capex หด 30% ต่อเนื่อง 2 ปี NVDA กระทบหนักสุด (ตรงข้าม MSFT/AMZN ที่มีธุรกิจ core กันชน) |
| **[[META]]** | 7.93 | 🥈 Strong 🆕 | 9.0 | 9.0 | 6.0 | 7.0 | 7.5 | Cloud | Capex leader ($125-145B self-host) แต่เป็น**ลูกค้า**ไม่ใช่ผู้ขาย compute (Centrality รองจาก MSFT/GOOGL/AMZN ที่ monetize คนนอกได้); Resilience สูงเพราะ ads engine เป็นรายได้หลักไม่พึ่ง AI capex โดยตรง (แม้ AI ช่วย monetization) |
| **[[AVGO]]** | 7.78 | 🥈 Strong 🆕 | 8.5 | 9.5 | 5.5 | 8.0 | 6.0 | CPU/Custom Silicon | Custom ASIC duopoly (คู่ MRVL) กำลังขยาย customer roster เป็น 6 ราย + CXL entry ใหม่; RA* ลดจากหนี้ VMware + COT/share risk (GCP เพิ่ม vendor MediaTek/MRVL); Resilience กลางเพราะมี VMware/broadband/networking นอก AI ~40-50% |
| **[[LITE]]** | 7.50 | 🥈 Strong 🆕 | 9.0 | 9.0 | 6.0 | 7.5 | 4.0 | Optical | "ศูนย์กลางจักรวาล CPO" ตามคำ Warren เอง — NVDA ลงทุน dual-source $2B พร้อม COHR ยืนยัน chokepoint จริง; Resilience ต่ำเพราะรายได้ optical ผูกกับ datacenter/AI buildout เป็นหลัก |
| **[[ARM]]** | 7.33 | 🥈 Strong 🆕 | 8.5 | 7.5 | 5.0 | 7.0 | 7.5 | CPU/Custom Silicon | Royalty เก็บได้ไม่ว่าใครชนะ ISA (แม้ NVDA/AMD/hyperscaler in-house ก็ยังใช้ ARM core); AGI CPU ชิปสำเร็จรูปตัวแรกในประวัติศาสตร์บริษัท มี demand แล้ว **$2B+ ตั้งแต่เปิดตัว, Meta เป็น lead partner** — แต่ margin silicon (~mid-30s) ต่ำกว่า legacy IP-royalty (~65%) มาก; RA* ลดจาก FTC antitrust overhang; **Resilience สูงสุดในกลุ่มเซมิ** เพราะฐาน royalty กระจายทั้ง smartphone/IoT/auto ไม่ใช่แค่ AI server |
| **[[AMD]]** | 7.30 | 🥈 Strong 🆕 | 8.5 | 9.0 | 6.0 | 6.5 | 5.0 | CPU/Custom Silicon | Venice EPYC + Helios rack ramp จริง + 6GW OpenAI deal; Centrality รองจาก NVDA/AVGO เพราะยังตามหลังใน CUDA-equivalent ecosystem |
| **[[AAPL]]** | 7.05 | 🥈 Strong 🆕 | 9.5 | 6.0 | 7.0 | 3.0 | 9.0 | Consumer/Edge | คุณภาพธุรกิจสูงสุดในธีม (ecosystem moat 40+ปี, Resilience สูงสุดเพราะรายได้แทบไม่ผูก AI capex เลย) — แต่ **Centrality/GP ต่ำสุดในกลุ่ม Core/Strong** เพราะเป็น agentic AI laggard ชัดเจน: Siri เวอร์ชันใหม่ (H2 2026) ใช้ **Google Gemini เป็น foundation model หลัก (จ่าย ~$1B/ปีให้ GOOGL)** แทนที่จะพัฒนา in-house model เอง — ยืนยันว่า AAPL ได้ประโยชน์จาก distribution/ecosystem มากกว่าเป็นผู้นำเทคโนโลยี agentic เอง — TQR ยังติด Strong เพราะคุณภาพพื้นฐานสูง ไม่ใช่เพราะมีบทบาทในธีม |
| **[[COHR]]** | 6.88 | 🥉 Peripheral 🆕 | 7.5 | 8.0 | 6.0 | 6.5 | 5.5 | Optical | InP/light-source moat กว้างกว่าที่เคยประเมิน (6-inch line yield เหนือ 3-inch) แต่ยังเป็นรอง LITE เฉพาะตลาด high-power-CW-laser-for-CPO-switch |
| **[[MU]]** | 6.55 | 🥉 Peripheral 🆕 | 7.5 | 9.0 | 5.0 | 5.0 | 5.0 | Memory | Bit-share model ล่าสุดวาง MU ที่ 3 ห่าง (20%) ต่ำกว่า Samsung(41%)/SK Hynix(39%); GP สูงจาก demand จริงแต่ Centrality ต่ำเพราะไม่ใช่ leader ที่แทนไม่ได้ + China CXMT ไล่ตามเร็ว; RA* ปรับขึ้นเล็กน้อยจาก **16 Strategic Customer Agreements มูลค่ารวม ~$100B** ที่ล็อครายได้ล่วงหน้า (ลด customer-concentration/cyclical risk เชิงโครงสร้าง แม้ market-share ยังเป็นรอง) |
| **[[SKHY]]** | 6.50 | 🥉 Peripheral 🆕 | 7.5 | 8.5 | 4.5 | 6.0 | 4.5 | Memory | ผู้นำ HBM อันดับ 1 จริงวันนี้ (**56.4% share, operating margin 72% — Q1 2026**) แต่ forecast 2027E ถูก Samsung แซง (41% vs 39%) — RA*/Centrality ลดเพราะไม่ใช่ผู้เล่นที่แทนไม่ได้ระยะยาว (competition จาก Samsung สูงขึ้นเรื่อยๆ แม้ปัจจุบันยังนำ) |
| **[[SPCX]]** | 6.12 | 🥉 Peripheral 🆕 | 7.5 | 9.0 | 2.5 | 4.0 | 6.0 | Frontier/Speculative | Pre-IPO ไม่มี track record (บังคับ ≤Speculative ตาม Tier rule) — RA* ต่ำสุดจาก key-man extreme + ไม่มีงบ audited public; มีรายได้ compute จริงผ่านสัญญา **COLOSSUS/COLOSSUS II กับ Anthropic ($45B/3ปี)** + xAI/Grok ควบรวมเข้าบริษัท (ก.พ. 2026) — แต่สัญญา terminable ทุก 90 วัน ทำให้ resilience ของรายได้ส่วนนี้ต่ำกว่าตัวเลขหัวข่าว; Terafab ระยะยาวยังเป็นการเดา ไม่ใช่ของจริงในงบ |

**ไม่มีตัวใด TQR < 5.5 (Out) ในรอบนี้** — ทุกตัวใน watchlist ที่ติดธีมยังผ่านเกณฑ์ขั้นต่ำ Peripheral

**กฎเหล็ก TQR ที่ยึดตอนให้คะแนน:** ไม่มีคำว่า "ถูก/แพง/discount/MoS" ในเหตุผลข้างต้นข้อใดเลย — ทุกคะแนนอิงธุรกิจ/ตำแหน่งในธีมเท่านั้น

---

## 5. KPI & Falsifier Dashboard

| KPI | ค่าปัจจุบัน | ค่าครั้งก่อน | ทิศทาง | เส้นที่ thesis แตก | แหล่ง |
|---|---|---|---|---|---|
| Big Tech 4 AI capex (YoY) | ~$725B, +77% YoY (2026) | ~$410B (2025) | ⬆️ เร่งตัว | หดตัว YoY จริง 2 ไตรมาสติด (ไม่ใช่แค่ growth ชะลอ) | GOOG/MSFT/AWS/META Q1-Q2 2026 earnings |
| Anthropic ARR MoM growth (ecosystem demand proxy) | ~13% MoM (May→Jun: $53B→$60B+) | ~50% MoM (Apr/May read) | ⬇️ **ชะลอ — ใกล้เส้น** | <20% MoM ต่อเนื่อง 2+ เดือน **ด้วยเหตุผลฝั่ง demand** (ไม่ใช่ throughput cap ชั่วคราว) | FundaAI Weekly nowcast, AI-Infrastructure.md |
| TSMC advanced-packaging socket retention | 1 socket loss ยืนยันแล้ว (Google TPU9 → Intel EMIB-T) | 0 (ก่อนหน้าเป็น overflow เท่านั้น ไม่ใช่ socket loss) | ⬇️ **แตะเส้นบางส่วน** | เพิ่มเป็น 2nd hyperscaler (Apple/Meta) ยืนยันใช้ EMIB-T จริง | Tech Taiwan 06-12; checkpoint Q3 2026 EMIB-T engineering samples |
| HBM bit-share leadership (2027E forecast) | SK Hynix 39% vs Samsung 41% (forecast) | SK Hynix ~parity 40/40 (prior read) | ⬇️ ต่อ SKHY | Samsung ชนะจริงในไตรมาสที่รายงานจริง (ไม่ใช่แค่ forecast) | UBS 08-Jun-2026 |
| Server DDR contract price QoQ | +60% (2Q26) | +37% (1Q26) | ⬆️ เร่งตัว | QoQ ราคาลด (สัญญาณ cycle rollover) | UBS Memory Semis Monthly |
| China commodity DRAM cost gap (CXMT vs Micron) | ~10% (ปิดจาก 30-40%) | 30-40% | ⬇️ ต่อ MU/SKHY | gap <5% + CXMT scale >400K wpm | Tech Taiwan 07-24 |
| Hyperscaler capex financing mix (self-fund→debt→equity) | ~94% ของ OCF หลัง buyback; GOOGL ระดมทุน equity $85B (Jun 2026) | ส่วนใหญ่ self-funded FCF (2025) | ⬇️ risk เพิ่ม | Big 4 รายใดถูกบังคับตัด capex guide เพราะข้อจำกัดด้านการเงิน/เครดิต | SemiAnalysis "Meta Compute" 07-02; Google equity raise piece |

**kpi_breach_count = 0** — ยังไม่มีตัวไหน "แตก" เต็มเส้น แต่ 2 ตัว (Anthropic ARR MoM, TSM packaging socket) ใกล้เส้นพอที่ต้องติดตามใกล้ชิดรอบหน้า — ทั้งคู่มีคำอธิบายที่ไม่ใช่ demand destruction (throughput cap ชั่วคราว / socket เดียวยังไม่ลาม) แต่ถ้ารอบหน้ายังไม่กลับทิศ = ต้องพิจารณา breach จริง

---

## 6. Cycle Stage

**เฟสปัจจุบัน: Build-out** — capex ยังเร่งตัว (+77% YoY), supply ยังตามหลัง demand ทุก layer (ASML/TSM ปรับ guide ขึ้นซ้ำ), NVDA เพิ่งเข้า production รุ่นใหม่ (Vera Rubin) ไม่ใช่ mature roadmap

**สัญญาณที่จะบอกว่าเปลี่ยนเฟส (Build-out → Monetization):**
- Enterprise/agentic revenue growth rate (Anthropic ARR, Bedrock, Copilot seats) เริ่มโตเร็วกว่า infra capex growth rate อย่างชัดเจนและต่อเนื่อง (ตอนนี้ capex ยังโตนำ)
- Hyperscaler เริ่ม guide capex "flat/slow growth" พร้อมกับ AI revenue ที่ยัง accelerate (แปลว่า infra ที่ลงทุนไปแล้วเริ่มพอสำหรับ monetize แทนที่จะสร้างเพิ่ม)
- Layer bottleneck เปลี่ยนจาก hardware/physical (memory/optical/packaging) ไปเป็น software/adoption (enterprise sales cycle, integration)

**Layer ที่ควรหนักในเฟส Build-out:** Compute, Memory, Optical, Equipment, Foundry/Packaging (ของแท้ hardware-scarcity) — Cloud/Hyperscaler ยังได้ประโยชน์ผ่าน backlog visibility แต่ pure infrastructure layer คือจุดที่ scarcity value สูงสุดตอนนี้

---

## 7. Review Log

| วันที่ | Evidence ใหม่ | Conviction เดิม→ใหม่ | TQR band ที่ขยับ | KPI breach |
|---|---|---|---|---|
| 2026-07-27 | **สร้าง playbook v1 ครั้งแรก** — สรุป Cross-Stock Intelligence + Warren's View จาก 8 sub-trend files (\`/Users/wittayanan/Desktop/Research/warren/trends/\`) + ตัดสินใจดึง **CPU-Renaissance เข้าเป็น sub-trend ที่ 9 ของ 🎯 AI Revolution** (TREND_MAP เคย flag ไว้ 07-27 ว่า conviction ขึ้น HIGH แล้ว แต่รอ /warren theme ตัดสิน — เหตุผล: CPU/agentic compute story ผูกกับ AI Revolution แนบแน่น ผ่าน NVDA Vera CPU $20B + ARM/AMD royalty capture, ไม่ใช่เดิมพันแยก) + คำนวณ TQR ครั้งแรกทุก 16 ticker + ตอบ 3 คำถาม Staleness Protocol ด้านล่าง | N/A (ใหม่) → **HIGH** | N/A (v1 — ยังไม่มีรอบก่อนหน้า) | 0 (แต่ flag Anthropic ARR MoM deceleration + TSM packaging socket-loss ให้ติดตามใกล้ชิดรอบหน้า) |
| 2026-07-27 | **Cross-check กับ public trend pages ที่เพิ่ง sync** (\`oat-investment-knowledge/knowledge/trends/*.md\`, commit \`d06449e\`+\`0711137\` — sync ย่อหน้า "## หุ้นที่ได้ประโยชน์" ให้ตรง TREND_MAP Key Stocks) พบ 4 ข้อมูลใหม่ที่ต้องปรับ TQR notes ก่อน commit v1: (1) **MU มี 16 SCA มูลค่า ~$100B ล็อครายได้ล่วงหน้า** → RA* ปรับ 4.5→5.0, TQR 6.47→6.55 (สลับอันดับกับ SKHY ในตาราง) (2) **SKHY share ปัจจุบัน 56.4% + operating margin 72% (Q1'26)** ระบุตัวเลขชัดแทนคำกว้างๆ (ไม่กระทบคะแนน) (3) **SPCX มีสัญญา COLOSSUS/COLOSSUS II กับ Anthropic $45B/3ปี (terminable ทุก 90 วัน) + ควบ xAI/Grok** แทนที่จะอ้างอิงแค่ Terafab เชิงเก็งกำไร (ไม่กระทบคะแนน — 90-day termination ยังเป็นความเสี่ยง resilience เดิม) (4) **AAPL Siri ใหม่จ่าย GOOGL ~$1B/ปีใช้ Gemini เป็น foundation model** — หลักฐานเชิงรูปธรรมยืนยัน laggard status เดิม (ไม่กระทบคะแนน) — ⚠️ พบ note คลาดเคลื่อนใน public AI-Infrastructure.md ว่า "META ไม่อยู่ watchlist" (ผิด — META อยู่ใน watchlist ปัจจุบัน) ไม่ใช่ขอบเขตของ \`/warren theme\` แก้ — flag ให้ Kim ส่งต่อทีมเว็บ/Pete ตรวจแยก | ไม่เปลี่ยน (HIGH คงเดิม) | MU/SKHY สลับอันดับ (ไม่ข้าม band) | 0 |

**Staleness Protocol (2026-07-27):**
1. **Evidence เดิมยังใช้ได้ไหม?** — N/A รอบนี้เป็นการสร้างครั้งแรก ไม่มี evidence เดิมของ playbook ให้ตรวจสอบ
2. **Counter-evidence ใหม่ที่พบระหว่างสร้าง:** (a) Google TPU9 เลือก Intel EMIB-T แทน TSMC CoWoS — TSM เสีย socket จริงครั้งแรก ไม่ใช่แค่ overflow (b) UBS ปรับ HBM 2027E bit-share ให้ Samsung แซง SK Hynix (41% vs 39%), Micron ตกเป็นอันดับ 3 ห่าง (20%) (c) CXMT (China) ปิด cost gap DRAM เหลือ ~10% จาก 30-40% เร็วกว่าคาด (d) Anthropic ARR MoM growth ชะลอจาก ~50% เหลือ ~13% (แม้มีคำอธิบายเชิง throughput-constraint)
3. **Conviction เปลี่ยนไหม?** — ตั้งเป็น HIGH ครั้งแรก (ตรงกับ TREND_MAP ทุก sub-trend HIGH) โดยอิงหลักฐานสะสมใน §2 (capex เร่ง, ASML/TSM guide ขึ้นซ้ำ, Vera Rubin production จริง) มากกว่า counter-evidence ข้างต้นซึ่งเป็นความเสี่ยงเฉพาะจุด (packaging socket, memory share, China catch-up) ไม่ใช่สัญญาณว่าธีมทั้งก้อนกำลังพัง`
  }
];