// Auto-generated by generate_trends.py — do not edit manually
// Last generated: 2026-07-27
var TRENDS_DATA = [
  {
    tag: "AI-Infrastructure",
    title: "โครงสร้างพื้นฐาน AI: มหาสงครามแห่งการลงทุน",
    subtitle: "เมื่อ Big Tech ทุ่ม $725 พันล้านดอลลาร์ในปีเดียว คำถามไม่ใช่ว่าใครจะชนะ แต่ว่าใครจะส่งของได้ทัน",
    conviction: "HIGH",
    last_updated: "2026-05-16",
    summary: "ลองนึกภาพการก่อสร้างเมืองใหม่ทั้งเมืองในเวลาห้าปี ไม่ใช่บ้านสองสามหลัง แต่เป็นโครงสร้างพื้นฐานทั้งหมด ตั้งแต่ถนน ระบบไฟฟ้า ท่อน้ำ ไปจนถึงตึกสูง นั่นคือสิ่งที่กำลังเกิดขึ้นในโลกของ AI datacenter ในขณะนี้",
    tickers: ["NVDA", "AVGO", "MRVL", "TSM", "MSFT"],
    content: `# โครงสร้างพื้นฐาน AI: มหาสงครามแห่งการลงทุน
*เมื่อ Big Tech ทุ่ม $725 พันล้านดอลลาร์ในปีเดียว คำถามไม่ใช่ว่าใครจะชนะ แต่ว่าใครจะส่งของได้ทัน*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ลองนึกภาพการก่อสร้างเมืองใหม่ทั้งเมืองในเวลาห้าปี ไม่ใช่บ้านสองสามหลัง แต่เป็นโครงสร้างพื้นฐานทั้งหมด ตั้งแต่ถนน ระบบไฟฟ้า ท่อน้ำ ไปจนถึงตึกสูง นั่นคือสิ่งที่กำลังเกิดขึ้นในโลกของ AI datacenter ในขณะนี้

Big Tech 4 ได้แก่ Google, Microsoft, Amazon, และ Meta ประกาศงบลงทุน CapEx รวมกัน ~$725B สำหรับปี 2026 เพิ่มขึ้น 77% จากปีก่อน ตัวเลขนี้ไม่ใช่แค่ตัวเลขที่ใหญ่ มันคือสัญญาณที่ชัดเจนว่าบริษัทเหล่านี้เชื่อว่า AI จะเปลี่ยนโลกธุรกิจอย่างถาวร และใครที่มีโครงสร้างพื้นฐานพร้อมก่อน คือผู้ชนะ

สิ่งที่น่าสนใจคือ จุดคอขวดของการแข่งขันได้เปลี่ยนแปลงไปอย่างรวดเร็ว ปี 2023-2024 ทุกคนแย่งกัน GPU ของ NVIDIA ปี 2024-2025 จุดคอขวดย้ายมาที่หน่วยความจำ HBM ปี 2026 สถานการณ์ซับซ้อนขึ้นอีกระดับ เพราะตอนนี้ทุกส่วนในระบบกลายเป็นปัญหาพร้อมกัน ทั้ง networking bandwidth, ระบบไฟฟ้า, advanced packaging, และ optical interconnects ต่างกลายเป็นคอขวดพร้อมๆ กัน

## ทำไมถึงน่าสนใจตอนนี้

NVIDIA เป็นกรณีศึกษาที่ชัดเจนที่สุด บริษัทรายงานรายได้รายไตรมาสที่ ~$68B และกำลังนำทางสู่ ~$78B ในไตรมาสถัดไป นั่นคือการเติบโต $10B ในหนึ่งไตรมาส ซึ่งเป็นอัตราที่ไม่เคยเกิดขึ้นกับบริษัทเทคโนโลยีในประวัติศาสตร์ NVIDIA ยังลงทุน $12B+ ในบริษัทในระบบนิเวศในเวลาเพียง 4 เดือน ทั้ง Synopsys, CoreWeave, Coherent, Lumentum, Marvell ซึ่งบอกให้รู้ว่าบริษัทกำลังสร้างเครือข่ายของซัพพลายเออร์ที่ผูกติดกับตัวเองอย่างถาวร

TSMC ซึ่งเป็นโรงงานผลิตชิปหลักของโลก รายงานรายได้ Q1 2026 ที่ $35.9B (+40.6% YoY) โดยระบุว่าความจุสายการผลิต N3 "ตึงมากจนถึงปี 2027" และปรับคาดการณ์รายได้ทั้งปีขึ้นเป็น >30% YoY โดยให้เหตุผลตรงๆ ว่า "agentic AI" คือแรงขับเคลื่อน สัญญาของ Cloud: GCP backlog ของ Google อยู่ที่ $460B เกือบเพิ่มเป็นสองเท่าในหนึ่งไตรมาส ขณะที่ AWS backlog อยู่ที่ $364B (+49% QoQ) ตัวเลขเหล่านี้คือคำสั่งซื้อจริงจากลูกค้าจริง ไม่ใช่การคาดการณ์

ASML ซึ่งเป็นบริษัทเดียวในโลกที่ผลิตเครื่อง EUV lithography ปรับคาดการณ์รายได้ปี 2026 ขึ้นเป็น €36-40B พร้อมเตือนล่วงหน้าว่าจะเกิดการขาดแคลน EUV supply ในปี 2027 ซึ่งแปลว่าการขยายกำลังการผลิตชิปขั้นสูงจะถูกจำกัดโดยเครื่องมือ ไม่ใช่เงินทุน

## หุ้นที่ได้ประโยชน์

**Core Infrastructure (ได้ประโยชน์โดยตรง)**

**[[NVDA]]** คือหัวใจของ trend นี้ GPU ของ NVIDIA เป็นพื้นฐานของ AI training และ inference ทั่วโลก ระบบ CUDA ecosystem ที่สร้างมา 15 ปีทำให้นักพัฒนาผูกติดกับ NVIDIA แทบจะเปลี่ยนไม่ได้ในระยะสั้น บริษัทกำลังเปลี่ยนจากการขาย GPU ชิ้นเดียวมาเป็นการขายระบบ "AI factory" แบบครบวงจร (NVL72, NVL144, NVL576) ซึ่งเพิ่มมูลค่าต่อการขายได้หลายสิบเท่า

**[[AVGO]]** (Broadcom) สร้างชิป ASIC แบบ custom สำหรับ hyperscalers รายใหญ่ รายได้ datacenter อยู่ที่ $6.1B ปี FY2026 โดยตั้งเป้าที่ $15B ในปี FY2028 นอกจากนี้ยัง CPO (Co-Packaged Optics) อยู่ใน volume production แล้ว

**[[MRVL]]** (Marvell) เป็น custom silicon platform ที่โตเร็วที่สุด รายได้ $8.2B FY2026 เป็น all-time high โดย 74% มาจาก datacenter พร้อม deal $2B จาก NVIDIA ที่ยืนยัน strategic importance

**[[TSM]]** (TSMC) คือโรงงานผลิตชิปที่ทุกคนต้องพึ่ง ไม่มีทางเลือกอื่นสำหรับ advanced node และ moat นี้แข็งแกร่งขึ้นทุกปี

**Cloud Hyperscalers**

**[[MSFT]], [[GOOGL]], [[META]], [[AMZN]]** ได้ประโยชน์ทั้งในฐานะผู้ซื้อ infrastructure (ที่กำลัง monetize ผ่าน AI services) และผู้ลงทุนในโครงสร้างพื้นฐาน Azure เติบโต +39% YoY, GCP +63% YoY, AWS AI revenue run-rate >$15B และยังขาด capacity อีก

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัทที่ขายเซิร์ฟเวอร์แบบดั้งเดิมที่ไม่ได้ปรับตัวสู่ AI workloads เผชิญกับความเสี่ยงที่รายได้ถูก cannibolize โดย hyperscalers ที่สร้าง custom silicon เอง Intel ที่ยังพึ่งพารายได้ CPU แบบเก่ายังอยู่ในช่วงเปลี่ยนผ่านที่ยากลำบาก บริษัทที่ให้บริการ co-location datacenter แบบ legacy ที่ไม่มี AI cooling infrastructure อาจสูญเสีย workloads ไปยัง hyperscalers ที่มี dedicated AI infrastructure

## มุมมองระยะยาว

AI Infrastructure คือ secular trend ที่แข็งแกร่งที่สุดในรอบ 10 ปี ต่างจาก dotcom bubble ปี 2000 ที่ infrastructure สร้างก่อน demand ในครั้งนี้ demand มาก่อน เห็นได้จาก backlog ที่เป็น hard commitment จากลูกค้า การลงทุน $725B ในปี 2026 เพียงปีเดียวเป็นสัญญาณว่า trend นี้ไม่ได้จะหายไปใน 1-2 ปี แต่เป็น multi-year buildout ที่จะดำเนินต่อไปตลอดทศวรรษนี้

สิ่งที่จะเปลี่ยน thesis นี้ได้มีอยู่สองอย่าง: ภาวะเศรษฐกิจถดถอยรุนแรงที่ทำให้ enterprise IT budget หยุดชะงัก หรือการค้นพบ algorithmic breakthrough ที่ลดความต้องการ hardware ลงอย่างฉับพลัน ทั้งสองสถานการณ์เป็นไปได้แต่ไม่ใช่ base case ตราบใดที่ demand สำหรับ AI services ยังเติบโตในอัตรานี้
`
  },
  {
    tag: "Memory-Supercycle",
    title: "วงจร Memory ที่เปลี่ยนไปตลอดกาล",
    subtitle: "จากสินค้าโภคภัณฑ์ที่ขึ้นๆ ลงๆ สู่ส่วนประกอบที่ขาดไม่ได้ของ AI",
    conviction: "HIGH",
    last_updated: "2026-07-26",
    summary: "มีคำถามที่นักลงทุนถามมานานหลายทศวรรษว่า \"หุ้น memory ควรซื้อตอนไหน?\" คำตอบดั้งเดิมคือ \"ซื้อตอน down cycle ขายตอน up cycle\" เพราะ memory คือสินค้าโภคภัณฑ์ที่ราคาวนเวียนขึ้นลงตามกำลังการผลิตและ demand ของ consumer electronics",
    tickers: ["NVDA", "AMD", "AVGO", "MRVL"],
    content: `# วงจร Memory ที่เปลี่ยนไปตลอดกาล
*จากสินค้าโภคภัณฑ์ที่ขึ้นๆ ลงๆ สู่ส่วนประกอบที่ขาดไม่ได้ของ AI*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-07-26

---

## ภาพรวม — Trend นี้คืออะไร

มีคำถามที่นักลงทุนถามมานานหลายทศวรรษว่า "หุ้น memory ควรซื้อตอนไหน?" คำตอบดั้งเดิมคือ "ซื้อตอน down cycle ขายตอน up cycle" เพราะ memory คือสินค้าโภคภัณฑ์ที่ราคาวนเวียนขึ้นลงตามกำลังการผลิตและ demand ของ consumer electronics

แต่ตอนนี้สมการนั้นเปลี่ยนไปแล้ว

HBM (High Bandwidth Memory) คือหน่วยความจำรุ่นใหม่ที่ถูกออกแบบมาเพื่อ AI โดยเฉพาะ แทนที่จะเป็น DRAM แท่งยาวๆ ที่เสียบใน slot, HBM คือชิปหน่วยความจำที่ถูก stack กันเป็นชั้นๆ และวางชิดกับ GPU แทบจะสัมผัสกัน ทำให้ส่งข้อมูลได้เร็วกว่า DRAM ทั่วไปหลายสิบเท่า ในโลกที่ AI model ต้องการอ่านและเขียนข้อมูลหลายล้านล้านครั้งต่อวินาที HBM ไม่ใช่ optional เป็น mandatory

ประธานาธิบดีฝ่ายอเมริกาเหนือของ SK Hynix ประกาศต่อสาธารณะในสัมมนาที่ Silicon Valley เมื่อมีนาคม 2026 ว่า "memory is no longer a cyclical industry" ประโยคนี้สั้นมาก แต่ความหมายสำหรับนักลงทุนนั้นลึกมาก

## ทำไมถึงน่าสนใจตอนนี้

หลักฐานที่ชัดเจนที่สุดคือ SK Hynix ทำ operating margin 72% ใน Q1 2026 ซึ่งเป็นตัวเลขที่ปกติเห็นได้เฉพาะในธุรกิจ software หรือยา ไม่ใช่การผลิตชิป Samsung และ SK Hynix รวมกันทำ operating profit ใน Q1 2026 สูงกว่า TSMC ซึ่งเป็นสัญญาณที่ไม่เคยเกิดขึ้นมาก่อน

สิ่งที่เปลี่ยน structure ของอุตสาหกรรมอย่างถาวรคือ LTA (Long-Term Agreement) Micron เซ็นสัญญา 5 ปีครั้งแรกในประวัติศาสตร์ของบริษัท ราคาในสัญญาถูก lock ที่ระดับ Q2 2026 ซึ่งสูงกว่า baseline ก่อนหน้า 80-100% สิ่งที่ตามมาคือ downside cyclicality ถูกกำจัดออกจากโมเดลธุรกิจ เพราะไม่มีทาง cut price ต่ำกว่า floor ที่ตกลงกันไว้แล้ว

นอกจาก HBM ยังมี NAND ที่กำลังกลายเป็น demand vector ใหม่ที่ไม่มีใครคาดคิด ในระบบ agentic AI ที่ AI ต้องจำบทสนทนายาวหลายร้อย turns AI ต้องการที่เก็บ KV cache ขนาดใหญ่ LLM model ขนาด 70B parameter ที่ทำงานด้วย context 128K token ต้องการ KV cache มากถึง 150GB+ ซึ่งมากกว่า VRAM ของ H100 ที่มีเพียง 80GB ทางออกคือ spill cache ลงไปใน SSD (NAND) DeepSeek พิสูจน์แล้วว่าทำได้ด้วย cache hit rate 95%+ ซึ่งแปลว่า NAND SSD กำลังกลายเป็น tier ใหม่ของ memory ใน AI stack — โมเดลจีนอีกตัว (Kimi K3, ก.ค. 2026) ก็ยืนยันแนวโน้มเดียวกัน: แม้บีบอัด KV cache ได้ถึง 75% แต่ความต้องการ NAND/DRAM ในระดับ cluster กลับเพิ่มขึ้นสุทธิ เพราะการบีบอัดทำให้ระบบรองรับ concurrency และเก็บ session ได้นานขึ้น (Jevons Paradox)

Demand ของ memory ก็กว้างขึ้นเรื่อยๆ เกินกว่าแค่ HBM — agentic AI ต้องการ CPU มาช่วย orchestrate งานมากขึ้น สัดส่วน GPU ต่อ CPU กำลังลดจาก 5.4:1 (2023) เหลือ 2.4:1 (คาดการณ์ปี 2028) ตาม estimate ของ JPMorgan ซึ่งหมายความว่าทุก CPU ที่เพิ่มเข้ามาต้องการ DRAM มาตรฐานเพิ่มด้วย — เป็น demand leg ใหม่ที่ไม่ได้อยู่ใน thesis เดิมที่โฟกัสแค่ HBM

## หุ้นที่ได้ประโยชน์

**[[NVDA]]** ได้ประโยชน์ทางอ้อมแต่ชัดเจน เพราะทุก GPU generation ของ NVIDIA ต้องการ HBM มากขึ้นและเร็วขึ้น HBM คือ "เชื้อเพลิง" ของ GPU แต่ละตัว ถ้า HBM ไม่มี NVIDIA ขาย GPU ไม่ได้

**[[AMD]]** ใช้ HBM3E ใน MI300X accelerator ซึ่งเป็น AI chip หลักของ AMD การเติบโตของ AI accelerator revenue AMD ขึ้นอยู่กับการได้รับ HBM allocation จาก SK Hynix หรือ Micron

**[[AVGO]]** (Broadcom) Custom ASICs ของ Broadcom ทั้งหมดที่ทำให้ Google TPU, Meta MTIA, Amazon Trainium ต่างต้องใช้ HBM และ CoWoS packaging ก็รวม HBM attachment เป็นส่วนหนึ่งของกระบวนการ

**[[MRVL]]** (Marvell) มี CXL memory controller IP ที่ช่วยให้ hyperscalers สร้าง memory pooling ซึ่งช่วยใช้ HBM ให้มีประสิทธิภาพสูงขึ้น รวมถึง HBM4E Controller IP ที่ licensed ให้ hyperscalers โดยตรง

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัทที่ยังวิเคราะห์ memory ด้วย framework แบบเก่าและ short ในช่วง "peak" ซึ่งจริงๆ อาจไม่ใช่ peak อีกต่อไป กลุ่ม consumer electronics ที่พึ่งพา DRAM/NAND แบบดั้งเดิมยังเผชิญกับ demand ที่อ่อนแออยู่ เพราะ smartphone และ PC cycle ยังไม่ฟื้นตัว ซึ่งอาจสร้างความสับสนในการอ่านตัวเลขอุตสาหกรรม

การแข่งขันชิงส่วนแบ่งตลาด HBM ระหว่าง Samsung กับ SK Hynix ก็สูสีขึ้นเรื่อยๆ — ล่าสุด UBS ปรับประมาณการปี 2027 ใหม่ให้ **Samsung (41%) แซงหน้า SK Hynix (39%) เล็กน้อย** ส่วน Micron อยู่อันดับ 3 ห่างๆ ที่ 20% แม้ Micron จะมีความได้เปรียบด้านเทคโนโลยี/ความเร็วในการ mass-produce HBM4 ก่อนใคร แต่ความได้เปรียบด้านเทคโนโลยีนั้นไม่ได้แปลว่าจะได้ market share มากที่สุดเสมอไป

CXMT ของจีน (เพิ่ง IPO ที่เซี่ยงไฮ้ 27 ก.ค. 2026 มูลค่าสูงถึง 8.5 หมื่นล้านดอลลาร์) กลายเป็นผู้ผลิต DRAM รายใหญ่อันดับ 4 ของโลกแล้ว และข้อมูลใหม่ (ก.ค. 2026) พบว่าสามารถผลิต DDR5 (commodity DRAM รุ่นล่าสุด) ได้โดย**ไม่ต้องใช้เครื่อง EUV เลย** — ใช้เทคนิค multi-patterning แบบเดียวกับที่ Micron เคยใช้ก่อนเปลี่ยนมา EUV — ต้นทุนการผลิตห่างจากผู้นำตลาดแค่ราว 10% เท่านั้น (นักวิเคราะห์เคยคาดว่าจะห่างถึง 30-40%) นี่คือสัญญาณว่าคู่แข่งจีนไล่ตามเร็วกว่าที่ตลาดเคยประเมินไว้ในตลาด DRAM ทั่วไป — แต่ในส่วน HBM (หน่วยความจำสำหรับ AI โดยเฉพาะ) CXMT ยังตามหลัง SK Hynix/Micron/Samsung ราว 4 ปี เพราะยังติดข้อจำกัดเรื่อง EUV และ yield ทำให้ยังไม่ใช่ภัยคุกคามระยะสั้นต่อฝั่ง AI memory โดยตรง แต่เป็นความเสี่ยงเชิงโครงสร้างที่ต้องจับตาในตลาด DRAM ทั่วไปช่วงปี 2027 เป็นต้นไป

## มุมมองระยะยาว

thesis ของ Memory Supercycle มีสองเสาหลัก: HBM สำหรับ AI training/inference และ NAND สำหรับ KV cache ใน agentic AI ทั้งสองเสาต่างมี demand driver ที่เป็นอิสระจากกัน ทำให้แม้เสาหนึ่งอ่อนแอลง อีกเสาก็ยังค้ำอยู่ LTA structure ทำให้ floor ราคาถูก lock ไว้แล้ว ซึ่งลบ downside scenario แบบเก่าออกไป

สิ่งที่จะเปลี่ยน thesis นี้ได้คือ breakthrough ในเทคโนโลยี compression ที่ลดความต้องการ HBM ต่อ workload อย่างมีนัยสำคัญ หรือ hybrid bonding เร็วขึ้นจนเพิ่ม capacity ต่อ wafer ได้มากพอที่จะทำลาย supply/demand balance สำหรับนักลงทุนในหุ้นไทย การเล่น memory supercycle ได้ดีที่สุดผ่าน NVDA, AVGO, MRVL ซึ่งอยู่ในฝั่ง demand สำหรับ memory มากกว่าในฝั่ง supply โดยตรง
`
  },
  {
    tag: "Optical-Interconnect",
    title: "การปฏิวัติ Optical Interconnect: เมื่อแสงแทนที่ทองแดง",
    subtitle: "ทองแดงใช้ส่งสัญญาณ AI ไม่ได้อีกแล้ว อนาคตคือแสง",
    conviction: "HIGH",
    last_updated: "2026-07-26",
    summary: "ลองนึกถึงทางด่วนในกรุงเทพที่รถติดสนิท คุณสามารถขยายช่องทางได้ แต่มีข้อจำกัดทางกายภาพที่ทำให้ขยายต่อไม่ได้อีกแล้ว ไม่ว่าจะลงทุนเพิ่มเท่าไร นั่นคือปัญหาของสายทองแดงในโลก AI ปัจจุบัน",
    tickers: ["NVDA", "AVGO", "MRVL", "MSFT"],
    content: `# การปฏิวัติ Optical Interconnect: เมื่อแสงแทนที่ทองแดง
*ทองแดงใช้ส่งสัญญาณ AI ไม่ได้อีกแล้ว อนาคตคือแสง*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-07-26

---

## ภาพรวม — Trend นี้คืออะไร

ลองนึกถึงทางด่วนในกรุงเทพที่รถติดสนิท คุณสามารถขยายช่องทางได้ แต่มีข้อจำกัดทางกายภาพที่ทำให้ขยายต่อไม่ได้อีกแล้ว ไม่ว่าจะลงทุนเพิ่มเท่าไร นั่นคือปัญหาของสายทองแดงในโลก AI ปัจจุบัน

ทองแดงสามารถส่งสัญญาณดิจิทัลได้ดีในระยะสั้นและความเร็วปานกลาง แต่เมื่อ AI datacenter ต้องการส่งข้อมูลด้วยความเร็วสูงกว่า 200G/lane สัญญาณในสายทองแดงจะเสื่อมสลายภายในระยะไม่ถึง 1 เมตร ไม่ใช่เรื่องของคุณภาพทองแดง แต่เป็น physics ล้วนๆ ไม่มีทางแก้ได้ด้วยวิศวกรรม

ทางออกคือ optical interconnects หรือการส่งข้อมูลด้วยแสง ซึ่งไม่มีข้อจำกัดเรื่องระยะทางในระดับเดียวกับทองแดง และสามารถรองรับ bandwidth ได้สูงกว่าหลายเท่า ตอนนี้อุตสาหกรรมกำลังเปลี่ยนจากทองแดงมาสู่ optical ใน scale-out network (การเชื่อมต่อระหว่าง rack และระหว่างอาคาร) และกำลังเริ่มเปลี่ยนใน scale-up network (การเชื่อมต่อระหว่าง GPU ต่อ GPU ใน server เดียวกัน) ผ่านเทคโนโลยีที่เรียกว่า CPO (Co-Packaged Optics)

## ทำไมถึงน่าสนใจตอนนี้

วันที่ 2 มีนาคม 2026 NVIDIA ประกาศลงทุน $2B ใน Coherent และ $2B ใน Lumentum ในวันเดียวกัน พร้อมกับ multi-year purchase commitments วันที่ 31 มีนาคม 2026 NVIDIA ลงทุนเพิ่มอีก $2B ใน Marvell ซึ่ง target ที่แท้จริงคือ Celestial AI's Photonic Fabric เทคโนโลยี optical die-to-die interconnect ที่อยู่ใน Marvell รวมแล้ว NVIDIA ทุ่มเงิน $6B+ ใน supply chain ด้าน optics ในเวลาเพียงสองเดือน นี่คือสัญญาณที่ชัดที่สุดที่จะเห็นได้ว่า optical ไม่ใช่ trend ของอนาคต แต่คือ mandatory infrastructure สำหรับ AI generation ถัดไป

เมื่อวันที่ 12 มีนาคม 2026 AMD, Broadcom, Meta, Microsoft, NVIDIA, และ OpenAI ประกาศ optical MSA (Multi-Source Agreement) standards ใหม่พร้อมกัน 3 มาตรฐาน ซึ่งเป็นเรื่องผิดปกติมากที่คู่แข่งมาตกลงมาตรฐานร่วมกันในเวลาเดียวกัน เหตุผลคือทั้งหมดต้องการให้ ecosystem ขยายตัวเร็วพอกับ demand

Broadcom Tomahawk 5 CPO อยู่ใน volume production แล้ว NVIDIA Quantum-X photonic switch ก็เช่นกัน ฝั่ง Google ใช้ OCS (Optical Circuit Switching) ใน Virgo fabric ที่เชื่อม TPU 130,000 ตัวด้วย bisection bandwidth 47 Pb/s ตัวเลขเหล่านี้เกินขีดความสามารถของทองแดงไปแล้วอย่างไม่มีทางกลับ

## หุ้นที่ได้ประโยชน์

**[[NVDA]]** ได้ประโยชน์ในฐานะทั้งนักลงทุนและลูกค้าหลัก Quantum-X photonic switch ใน production และ CPO เป็นส่วนสำคัญของ roadmap สำหรับ Rubin และ Feynman generation ที่จะตามมา

**[[AVGO]]** (Broadcom) มี Tomahawk 5 CPO ใน volume production แล้ว และ custom ASIC networking สำหรับ hyperscalers ต้องรวม optics เป็นส่วนหนึ่งของ solution ตำแหน่งที่แข็งแกร่งใน scale-out network ทำให้ AVGO ได้ประโยชน์ทั้งในปัจจุบันและอนาคต

**[[MRVL]]** (Marvell) คือ optical DSP leader ในปัจจุบัน และผ่านการซื้อ Celestial AI มูลค่า $3.25B-$5.5B Marvell กำลังสร้าง Photonic Fabric ที่จะทำให้ optical die-to-die interconnect เป็นไปได้ โดยสร้าง unified optical memory pool ขนาด 33TB+ ซึ่งจำเป็นสำหรับ model พารามิเตอร์หลายล้านล้านตัวในอนาคต รายได้ Marvell อยู่ที่ $8.2B โดย 74% มาจาก datacenter

**[[MSFT]] และ [[GOOGL]]** ได้ประโยชน์ในฐานะ early adopter ที่ลดต้นทุน infrastructure ด้วยการใช้ CXL memory pooling ผ่าน optical และ OCS-based fabric ตามลำดับ

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

ผู้ผลิตสาย copper cable และ transceiver ดั้งเดิมที่ไม่ได้ลงทุนใน optical technology กำลังเผชิญกับการถูก displace อย่างช้าๆ บริษัทที่ผลิต InfiniBand copper หรือ direct-attach copper ในระดับ 400G+ จะเห็น TAM หดตัวตามการเปลี่ยนผ่านสู่ optical ใน 2-3 ปีข้างหน้า

ความเสี่ยงที่น่ากังวลสำหรับฝั่ง optical เองคือ InP (Indium Phosphide) ซึ่งเป็นวัสดุที่จำเป็นสำหรับ laser ใน EML ที่ความถี่ 1310nm/1550nm ไม่มีวัสดุทดแทน และคาดว่าจะขาดแคลน 3-5 ปี ซึ่งอาจจำกัด scaling ของทั้ง trend

## มุมมองระยะยาว

การเปลี่ยนผ่านจากทองแดงสู่ optical มีสามระยะชัดเจน ปัจจุบัน pluggable transceivers ที่ความเร็ว 800G กำลัง ramp ขึ้นพร้อมกับ 1.6T ที่เริ่มเข้ามา ระยะกลาง ปี 2026-2027 CPO จะ scale ใน scale-out network โดย Broadcom และ NVIDIA เป็น primary integrators ระยะยาว ปี 2028+ optical die-to-die ผ่าน Marvell Celestial AI Photonic Fabric จะ enable scale-up optical สำหรับ model ขนาดใหญ่ที่สุด

หุ้น optical pure-play บางตัวขึ้นไปแล้ว 900-1,700% ใน 12 เดือน แต่ใน watchlist ของเรา AVGO และ MRVL ยังมี upside จากระยะสองและสามที่ยังไม่ถูก price in อย่างเต็มที่ สิ่งที่จะเปลี่ยน thesis นี้ได้คือ CPO timeline slip ซึ่งจะทำให้ pluggable ยังขายได้นานขึ้น (จริงๆ เป็น positive ระยะสั้น) หรือ InP shortage ที่รุนแรงจนจำกัด scaling

## อัพเดท (2026-07-26) — 3 หลักฐานใหม่ยืนยัน thesis เดิม + 1 เรื่องต้องเข้าใจเรื่อง timing

**1. NVIDIA ล็อคซัพพลายเชนแสงจริง ~$6.5 พันล้านดอลลาร์ ภายใน 3 เดือน** — นอกจาก Coherent, Lumentum, Marvell ที่ลงทุนไปแล้ว NVIDIA ยังเติมอีก $0.5-3.2 พันล้านดอลลาร์ (แบบ warrant) ให้ Corning เพื่อขยายกำลังผลิตใยแก้วนำแสงในสหรัฐฯ 10 เท่า และกำลังผลิตไฟเบอร์เพิ่มกว่า 50% จุดสำคัญคือ NVIDIA เลือกลงทุนใน "ผู้ผลิตแสง" ถึง 2 ราย (Coherent + Lumentum) พร้อมกัน แทนที่จะเลือกรายเดียว — สัญญาณนี้บอกว่าจุดคอขวดจริงคือวัสดุที่ใช้ทำแสง (Indium Phosphide หรือ InP) ไม่ใช่แค่ตัวโมดูล และราคาแผ่นเวเฟอร์ InP ขนาด 6 นิ้วก็พุ่งขึ้น 250% (จาก 1,400 เป็น 5,000 ดอลลาร์) ยืนยันความขาดแคลนนี้จากราคาตลาดจริง

**2. ความกังวลเรื่องคู่แข่งจีนด้าน laser คลี่คลายลง (ไม่ใช่หายไป แต่ยังไม่ใช่ภัยระยะสั้น)** — งานวิจัยอิสระหลายชิ้นชี้ว่าผู้ผลิต laser จีนยังตามหลังผู้นำตลาดตะวันตก 1-2 generation ทั้งในแง่เทคโนโลยี (ยังไม่มีความสามารถผลิต laser กำลังสูงระดับ CPO หรือเวเฟอร์ 6 นิ้ว) และยังไม่ผ่านการรับรองคุณภาพจาก hyperscaler รายใหญ่ระดับโลก

**3. ข้อควรระวังเรื่อง timing:** ต้นเดือนมิถุนายน 2026 มีงานวิจัยชิ้นหนึ่งระบุว่าการผลิต CPO (Co-Packaged Optics) ในปริมาณมากจะเลื่อนจากที่คาดไว้ "ปี 2026" ไปเป็นปี 2028-2029 ทำให้หุ้นกลุ่ม optical ร่วงยกแผงในวันเดียว แต่เมื่อวิเคราะห์ลึกลงไปพบว่านี่คือการปรับเฉพาะ "ชั้นกลาง" ของเทคโนโลยีเท่านั้น — ธุรกิจ pluggable transceiver ที่เป็นรายได้หลักของบริษัท optical ในปัจจุบันไม่ได้รับผลกระทบเลย ส่วน scale-up (การเชื่อมต่อใน rack เดียวกัน) ก็ยังเป็นไปตามแผนเดิมที่ปี 2028 เป็นต้นไป **บทเรียนสำคัญ:** ทิศทางของเทคโนโลยีแสงยังชัดเจนเหมือนเดิม แต่ความเร็วในการกลายเป็นรายได้จริงต้องแยกพิจารณาต่างหาก — อย่าสับสนระหว่างสองเรื่องนี้

**4. สงครามภายใน "แร็ค" (Computex 2026):** ภายใน rack เดียวกัน (การเชื่อมต่อ GPU กับ GPU ระยะสั้นที่สุด) ทองแดงยังคงได้เปรียบไปอีก 2-3 ปีข้างหน้า ผ่านสถาปัตยกรรมใหม่ที่เรียกว่า "Copper 2.0" (midplane connector ที่ลดจำนวนสายทองแดงลงมาก) ก่อนที่ NVIDIA จะเปลี่ยนไปใช้ระบบไร้สายทองแดงเต็มรูปแบบในรุ่น Kyber ช่วงปลายปี 2027 — นี่ยืนยัน pattern เดิมของ trend นี้ว่า "แสงชนะระยะไกลก่อนเสมอ แล้วค่อยๆ เข้าใกล้ตัวชิปมากขึ้น" ไม่ใช่เรื่องใหม่ที่กระทบ thesis
`
  },
  {
    tag: "Cloud-Acceleration",
    title: "Cloud CapEx Acceleration: เมื่อยักษ์ใหญ่ทุ่มพร้อมกัน",
    subtitle: "สามยักษ์ Cloud เพิ่มงบลงทุนพร้อมกันในขณะที่รายได้เร่งตัวขึ้น — นี่คือสัญญาณที่ดีที่สุดที่จะเห็นได้",
    conviction: "HIGH",
    last_updated: "2026-05-16",
    summary: "มีความเข้าใจผิดที่พบบ่อยในการวิเคราะห์หุ้นเทคโนโลยีว่า \"ถ้าบริษัทเพิ่มงบ CapEx มาก หมายความว่ากำไรจะลดลง\" ความเข้าใจนี้อาจถูกสำหรับบริษัททั่วไป แต่ผิดอย่างมีนัยสำคัญสำหรับ hyperscalers ในปี 2026",
    tickers: ["GOOGL", "MSFT", "AMZN", "META"],
    content: `# Cloud CapEx Acceleration: เมื่อยักษ์ใหญ่ทุ่มพร้อมกัน
*สามยักษ์ Cloud เพิ่มงบลงทุนพร้อมกันในขณะที่รายได้เร่งตัวขึ้น — นี่คือสัญญาณที่ดีที่สุดที่จะเห็นได้*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

มีความเข้าใจผิดที่พบบ่อยในการวิเคราะห์หุ้นเทคโนโลยีว่า "ถ้าบริษัทเพิ่มงบ CapEx มาก หมายความว่ากำไรจะลดลง" ความเข้าใจนี้อาจถูกสำหรับบริษัททั่วไป แต่ผิดอย่างมีนัยสำคัญสำหรับ hyperscalers ในปี 2026

ปี 2026 คือปีที่ cloud acceleration ได้รับการยืนยันอย่างเป็นทางการ ไม่ใช่เรื่องของการคาดการณ์อีกต่อไป GCP ของ Google เติบโต +63% YoY, Azure ของ Microsoft +39% YoY, AWS ของ Amazon +28% YoY ทั้งหมดนี้เกิดขึ้นในขณะที่ทั้งสามบริษัทประกาศเพิ่ม CapEx พร้อมกัน Google เพิ่มเป็น $180-190B, Microsoft $190B, Amazon $200B การที่ top-line เร่งตัวขึ้นพร้อมกับ CapEx เพิ่มขึ้นคือ configuration ที่ดีที่สุดเท่าที่จะเป็นไปได้ มันหมายความว่า demand นำหน้า supply ไม่ใช่ supply นำหน้า demand

สิ่งที่ยิ่งกว่านั้นคือ AI monetization flywheel กำลังกลายเป็นตัวเลขจริง Anthropic ซึ่งเป็น AI company ที่ AWS ลงทุนหลักมีรายได้ประจำปี (ARR) เติบโตจาก $1.8B ในเดือนกุมภาพันธ์ 2025 ไปสู่ $30B+ ในเดือนเมษายน 2026 คือ 16 เท่าใน 14 เดือน

## ทำไมถึงน่าสนใจตอนนี้

สิ่งที่ทำให้ปี 2026 แตกต่างจากปีก่อนๆ คือหลักฐานของ "committed demand" ที่เป็น hard contract GCP มี backlog $460B เกือบเพิ่มเป็นสองเท่าในหนึ่งไตรมาส AWS มี backlog $364B (+49% QoQ) Jeff Bezos บอกตรงๆ ว่าการลงทุน $200B ใน 2026 ไม่ได้มาจาก hunch แต่มาจาก "customer commitments for a substantial portion of 2027-2028 monetization" นี่คือสัญญาที่เซ็นแล้ว

AWS AI revenue run-rate เกิน $15B ใน Q1 2026 และยังอยู่ในสถานะ "capacity-constrained" หมายความว่ายังมี demand ที่รอ supply อยู่อีก AWS Bedrock ที่ให้บริการ AI model สำเร็จรูปมีรายได้เพิ่ม +170% QoQ โดย 80% ของ Fortune 100 ใช้งาน Bedrock แล้ว

AWS Trainium ซึ่งเป็น custom chip ที่ Amazon ออกแบบเองสำหรับ AI มี committed revenue $225B+ ถ้าคำนวณเป็น standalone บริษัท มันจะเป็น top-3 datacenter chip franchise ของโลก ตัวเลขนี้ถูก underpriced อย่างมากใน valuation ของ Amazon ในปัจจุบัน

META และ Amazon ซึ่งครั้งหนึ่งถูกมองว่าเป็น "AI laggard" ตอนนี้กลายมาเป็นสองบริษัทที่ leverage สูงที่สุดสำหรับ phase ถัดไปของ agentic AI

## หุ้นที่ได้ประโยชน์

**[[GOOGL]]** คือบริษัทที่มี AI monetization story ที่ครบเครื่องที่สุด ทั้ง GCP ที่โต +63%, backlog $460B, TPU 8th gen ที่เริ่มขาย externally, Gemini Enterprise ที่มี MAU เพิ่ม +40% QoQ และ compute-constrained ซึ่งหมายถึง demand มีมากกว่า capacity ที่มี

**[[MSFT]]** ได้ประโยชน์จาก Azure +39% YoY และ Copilot enterprise monetization ที่กำลัง ramp ขึ้น การเป็น exclusive partner ของ OpenAI ทำให้ทุก AI wave ใหม่ที่ OpenAI ออกมาแปลงเป็น Azure revenue โดยตรง

**[[AMZN]]** มี asymmetric upside ที่ดีที่สุดใน hyperscalers ทั้งสาม AWS custom silicon (Trainium) ที่ annualized >$20B โตด้วย triple-digit YoY rates ยังไม่ถูก price in อย่างเต็มที่ใน valuation ปัจจุบัน นอกจากนี้ AWS architecture ที่รวม CPU+storage+networking เป็นโครงสร้างที่เหมาะสมที่สุดสำหรับ agentic workloads

**[[META]]** ได้ประโยชน์จาก AI-enhanced ad monetization และการสร้าง Llama open-source ecosystem ที่ทำให้นักพัฒนาทั่วโลก build บน Meta infrastructure รายได้โฆษณาที่ดีขึ้นจาก AI targeting ทำให้ ROI สำหรับผู้โฆษณาดีขึ้น ซึ่ง reinforce ให้พวกเขาใช้จ่ายมากขึ้น

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัท SaaS ที่ให้บริการ generic tools โดยไม่มี AI differentiation จะเผชิญกับ pressure ต่อเนื่อง เพราะ hyperscalers กำลัง bundle AI capabilities เข้าใน platform ของตัวเองโดยไม่คิดราคาเพิ่ม บริษัท enterprise software ที่ไม่มี AI roadmap ที่ชัดเจนจะเสียส่วนแบ่งตลาดให้กับ cloud-native AI alternatives

## มุมมองระยะยาว

Cloud acceleration ไม่ใช่ one-year event แต่เป็น multi-year structural shift ที่ driven โดย agentic AI backlog ที่เซ็นสัญญาแล้วนั้น extend ไปถึง 2027-2028 ซึ่งแปลว่า revenue visibility ของ hyperscalers ดีกว่าบริษัทอื่นๆ ส่วนใหญ่ในตลาด

สิ่งที่จะทำให้ thesis นี้ช้าลงมากที่สุดคือ enterprise adoption ของ AI ที่ช้ากว่าที่คาด ในขณะที่ consumer AI adoption เร็วมาก enterprise มักมีอุปสรรคด้าน compliance และ security ที่ทำให้ deployment ช้ากว่า 1-2 ไตรมาส แต่ direction ยังชัดเจน hyperscalers จะเป็นผู้ชนะที่ใหญ่ที่สุดจาก AI transition ไม่ว่าจะเกิดขึ้นเร็วหรือช้าแค่ไหน
`
  },
  {
    tag: "Custom-Silicon",
    title: "Custom Silicon: เมื่อยักษ์ใหญ่ออกแบบชิปเอง",
    subtitle: "NVIDIA ไม่ได้จะหายไป แต่ตลาดชิป AI กำลังใหญ่พอที่จะมีผู้ชนะหลายคน",
    conviction: "HIGH",
    last_updated: "2026-05-16",
    summary: "ในโลกของ semiconductor มีกฎที่คนทั่วไปมักเข้าใจผิดว่า \"ถ้า Google หรือ Amazon ออกแบบชิปเอง นั่นหมายความว่า NVIDIA แพ้\" ความเข้าใจนี้ไม่ถูก และการเข้าใจว่าทำไมจึงไม่ถูกคือกุญแจสู่การเข้าใจ custom silicon trend นี้",
    tickers: ["AVGO", "MRVL", "GOOGL", "AMZN", "AMD"],
    content: `# Custom Silicon: เมื่อยักษ์ใหญ่ออกแบบชิปเอง
*NVIDIA ไม่ได้จะหายไป แต่ตลาดชิป AI กำลังใหญ่พอที่จะมีผู้ชนะหลายคน*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ในโลกของ semiconductor มีกฎที่คนทั่วไปมักเข้าใจผิดว่า "ถ้า Google หรือ Amazon ออกแบบชิปเอง นั่นหมายความว่า NVIDIA แพ้" ความเข้าใจนี้ไม่ถูก และการเข้าใจว่าทำไมจึงไม่ถูกคือกุญแจสู่การเข้าใจ custom silicon trend นี้

CUDA ecosystem ของ NVIDIA ที่สร้างมา 15 ปีทำให้นักพัฒนาหลายล้านคนเขียนโค้ดบน NVIDIA platform โดยตรง การย้ายออกจาก CUDA ไม่ใช่เรื่องของแค่เปลี่ยนชิป แต่คือการ rewrite software stack ทั้งหมด ซึ่งมีต้นทุนสูงมาก ดังนั้น hyperscalers ที่ออกแบบชิปเองไม่ได้ทำเพื่อ replace NVIDIA แต่ทำเพื่อ complement ในกรณีที่ NVIDIA แพงเกินไปหรือช้าเกินไปสำหรับ specific workload

Custom silicon ทำงานได้ดีที่สุดกับ workload ที่ predictable และ high-volume เช่น recommendation systems, ad targeting, หรือ specific inference tasks ที่รู้ล่วงหน้าว่าต้องการ compute แบบไหน ในขณะที่ NVIDIA GPU ดีที่สุดสำหรับ flexible, general-purpose training และ research ทั้งสองอยู่ร่วมกันได้

Broadcom และ Marvell คือสองบริษัทที่ได้ประโยชน์สูงสุดจาก trend นี้ ในฐานะ "custom silicon foundry" ที่ออกแบบชิปให้ hyperscalers โดยใช้ IP ของตัวเองรวมกับ spec จากลูกค้า

## ทำไมถึงน่าสนใจตอนนี้

AWS Trainium เป็น case study ที่ดีที่สุด Amazon ออกแบบ Trainium เองสำหรับ AI training โดยมีประสิทธิภาพราคาต่อ performance ดีกว่า GPU เทียบเท่า 30% Trainium2 ขาย sold out แทบจะทันที Trainium3 ที่เพิ่งเริ่ม ship ใน early 2026 ก็ถูกจอง "largely spoken for" แล้ว ถ้าคำนวณ Trainium เป็น standalone บริษัท รายได้ annualized >$20B ทำให้เป็น top-3 datacenter chip franchise ของโลก และยังมี committed revenue $225B+ ที่รอ deliver

Marvell FY2026 revenue $8.2B ซึ่งเป็น all-time high โดย 74% มาจาก datacenter ตั้งเป้าว่าจะถึง $15B ใน FY2028 NVIDIA ลงทุน $2B เชิงกลยุทธ์ใน Marvell ในเดือนมีนาคม 2026 ซึ่งเป็นการ "stamp of approval" ต่อสาธารณะว่า Marvell's custom silicon platform มีความสำคัญต่อ NVIDIA roadmap

Broadcom FY2026 datacenter revenue $6.1B (+46.5% YoY) โดยตั้งเป้า $15B ใน FY2028 ลูกค้าหลักคือ Google (TPU), Meta (MTIA), Amazon (Trainium) — ทุกบริษัทที่ทุ่มงบ CapEx หลักล้านล้านบาทใน AI

NVIDIA เองประกาศ NVLink Fusion platform ที่ GTC 2026 ซึ่ง enable ให้ custom XPUs จากบริษัทอื่น interoperate กับ NVIDIA infrastructure การเปิด platform นี้แปลว่า NVIDIA ยอมรับว่า custom silicon จะเติบโตและเลือกที่จะ enable แทนที่จะ fight

## หุ้นที่ได้ประโยชน์

**[[AVGO]]** (Broadcom) คือ บริษัทที่ได้ประโยชน์โดยตรงที่สุดจาก hyperscaler custom silicon trend สองโปรแกรม hyperscaler ASIC หลักของ Broadcom ต่างมีเป้าหมายรายได้ >$15B ต่อโปรแกรมใน FY2028 ซึ่งรวมกันเกินกว่าขนาด revenue ปัจจุบันทั้งบริษัท

**[[MRVL]]** (Marvell) คือชื่อที่ undervalued ที่สุดใน watchlist เมื่อเทียบกับ conviction ที่มี custom XPUs บน NVLink Fusion, revenue $8.2B ที่โตสู่ $15B ใน FY2028, NVIDIA strategic investment และ Celestial AI Photonic Fabric ที่เป็น option ฟรีสำหรับ optical die-to-die interconnect รายได้ปลายปี 2028 ทั้งหมดนี้ยังซื้อขายในราคาที่ discount Broadcom อย่างมีนัยสำคัญ

**[[GOOGL]]** TPU 8th generation เริ่มขาย externally ให้ลูกค้า GCP แล้ว ซึ่ง validate ว่า custom silicon ของ Google ดีพอที่จะ compete กับ NVIDIA ในหลาย workload Axion CPU ประกอบกับ TPU ทำให้ cost per AI workload ดีกว่า NVIDIA 2x+

**[[AMZN]]** Graviton CPU ที่ ARM-based ได้รับความไว้วางใจจาก 98% ของ top 1,000 EC2 customers แม้แต่ Meta ก็ commit tens of millions ของ Graviton cores นี่คือ market validation ที่ทรงพลัง

**[[AMD]]** มี EPYC server CPU ที่กำลังได้ market share และ MI300X ที่เป็น competitive option สำหรับ AI inference แต่ AMD ใช้ Broadcom/Marvell custom silicon platforms ไม่ใช่สร้างเองทั้งหมด ดังนั้น AMD ได้ประโยชน์บางส่วนจาก trend นี้ แต่ไม่เต็มเม็ดเต็มหน่วย

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

สิ่งที่น่ากังวลสำหรับ custom silicon ecosystem คือในระยะ 5-7 ปี hyperscalers อาจตัดสินใจ in-house ทุกอย่างและ bypass Broadcom/Marvell ไปเลย Google ทำ TPU เองทั้งหมดแล้ว Amazon มี Trainium เช่นกัน ความเสี่ยงนี้ real แต่ timeline ยาวมากและ Broadcom/Marvell มีเวลาปรับตัว

NVIDIA NVLink Fusion อาจกลายเป็น Trojan horse ที่ capture economics ของ custom silicon แทนที่จะ enable คนอื่น ถ้า hyperscalers depend on NVIDIA networking อยู่ดี NVIDIA ก็ยัง capture value อยู่

## มุมมองระยะยาว

Custom silicon เป็น theme ที่มี revenue visibility ที่ดีที่สุดใน semiconductor sector เพราะ committed revenue หลายปี จาก hyperscalers ที่เป็น investment-grade counterparties ไม่ใช่การคาดเดา รายได้ที่ Broadcom และ Marvell จะทำได้ใน FY2028 ส่วนใหญ่มาจากสัญญาที่เซ็นไว้แล้ว

ถ้า Marvell's Celestial AI Photonic Fabric ทำงานได้ตามแผนปลายปี 2028 มันจะเป็น game-changer สำหรับ trillion-parameter models ที่ต้องการ memory bandwidth มากกว่าที่ HBM จะให้ได้ ซึ่งเป็น upside ที่ตลาดยังไม่ได้ price in อย่างจริงจัง
`
  },
  {
    tag: "Agentic-AI",
    title: "Agentic AI: เมื่อ AI เริ่มทำงานแทนคนจริงๆ",
    subtitle: "จาก AI ที่ตอบคำถาม สู่ AI ที่รับงาน ทำงาน และส่งผลลัพธ์โดยไม่ต้องถามทุกขั้นตอน",
    conviction: "HIGH",
    last_updated: "2026-05-16",
    summary: "ช่วงปี 2023-2024 คนส่วนใหญ่ใช้ AI แบบ \"ถาม-ตอบ\" คุณพิมพ์คำถาม AI ตอบ คุณอ่าน ถ้าต้องการอะไรเพิ่ม ก็ถามใหม่ AI ทำงานเฉพาะเมื่อมีคนถาม และหยุดทันทีที่ตอบเสร็จ",
    tickers: ["NVDA", "META", "AMZN", "MSFT", "GOOGL", "PLTR"],
    content: `# Agentic AI: เมื่อ AI เริ่มทำงานแทนคนจริงๆ
*จาก AI ที่ตอบคำถาม สู่ AI ที่รับงาน ทำงาน และส่งผลลัพธ์โดยไม่ต้องถามทุกขั้นตอน*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ช่วงปี 2023-2024 คนส่วนใหญ่ใช้ AI แบบ "ถาม-ตอบ" คุณพิมพ์คำถาม AI ตอบ คุณอ่าน ถ้าต้องการอะไรเพิ่ม ก็ถามใหม่ AI ทำงานเฉพาะเมื่อมีคนถาม และหยุดทันทีที่ตอบเสร็จ

Agentic AI คือสิ่งที่แตกต่างอย่างสิ้นเชิง แทนที่จะตอบคำถาม AI รับ "ขอบเขตงาน" (scope of work) และทำงานให้เสร็จเองหลายชั่วโมงโดยไม่ต้องมีคนนั่งดูตลอดเวลา Claude Opus 4.6 ที่ออกมาวันที่ 5 กุมภาพันธ์ 2026 ถูกอธิบายโดยนักวิเคราะห์ว่าเป็น "ChatGPT moment สำหรับ agents" เป็นครั้งแรกที่ตลาดเห็นว่า AI สามารถทำงานหลายชั่วโมงแบบ autonomous และส่ง output เข้า production ได้โดยตรง

สิ่งที่ agentic AI เปลี่ยนแปลงในระดับ infrastructure นั้นสำคัญมาก เพราะ agentic workload ต้องการทรัพยากรพร้อมกันหลายมิติ: compute มากขึ้นต่อ user request เพราะ AI ต้องเรียก model หลายครั้งต่องาน, memory มากขึ้นเพราะต้องจำ context หลายร้อย turns, networking สำหรับ inter-agent communication, และ storage สำหรับ persistent context บน NAND ทั้งหมดนี้เกิดพร้อมกันทำให้ทุก infrastructure segment เห็น demand เร่งตัวขึ้นพร้อมกัน

## ทำไมถึงน่าสนใจตอนนี้

ตัวเลขที่บอกเล่าเรื่องราวได้ดีที่สุดคือ Anthropic ARR ที่เติบโตจาก $0.9B ปลายปี 2024 มาเป็น $9B ปลายปี 2025 และ $30B+ ในเดือนเมษายน 2026 คือ 16 เท่าใน 14 เดือน อัตรานี้เกินกว่า growth rate ของ Google และ Facebook ในช่วงที่เติบโตเร็วที่สุดของพวกเขา

ราคาเช่า H100 และ B200 เพิ่มขึ้น 20-22% ในสามเดือน เพราะ demand จาก agentic workloads ล้น capacity ที่มีอยู่ TSMC พูดถึง "massive compute requirements from transition to Agentic AI" เป็น explicit reason สำหรับการปรับคาดการณ์รายได้ขึ้นเป็น >30% YoY สำหรับทั้งปี

นักวิจัย AI หลายกลุ่มปรับ timeline ของ AGI ลงอย่างมีนัยสำคัญ: SWE-AGI (AI ที่เขียนโค้ดได้ดีกว่า software engineer ทั่วไป) คาดว่าจะเกิดขึ้นในปี 2026, White-collar AGI ปี 2026-2027, AI self-iteration ปี 2027-2028 นี่คือ timeline ที่บีบอัดลงจาก "5-10 ปี" เมื่อ 2 ปีก่อน

การวิเคราะห์ workload ของ DeepSeek V4 แสดงให้เห็นว่า agent workload มีลักษณะเฉพาะ: context เฉลี่ย 32,700 tokens, ส่งข้อมูลใหม่ 429 tokens ต่อ round แต่ 98.7% ของ history สามารถ reuse ได้ ซึ่ง validate ว่าการออกแบบ KV cache ที่ดีสำหรับ agentic ต่างจาก chatbot อย่างมีนัยสำคัญ

## หุ้นที่ได้ประโยชน์

**[[NVDA]]** ได้ประโยชน์มากที่สุดจาก agentic AI เพราะ inference infrastructure (ไม่ใช่แค่ training) คือ primary use case ทุก agent request เรียก GPU หลายครั้ง ต่างจาก chatbot ที่เรียกครั้งเดียว volume ของ GPU calls ต่อ user จึงสูงกว่ามาก

**[[META]]** ได้ประโยชน์สองทาง Llama open-source ecosystem สร้าง developer platform ที่ทำให้นักพัฒนาทั่วโลก build agents บน Meta infrastructure AI-enhanced ad system ได้ประโยชน์จากการที่ agents เข้าใจ user intent ได้ดีขึ้นอย่างมาก

**[[AMZN]]** มี architecture ที่เหมาะกับ agentic workloads มากที่สุด agent ต้องการ orchestration, tool calling, storage, และ networking ไม่ใช่แค่ GPU AWS มี CPU+storage+networking ครบในแพลตฟอร์มเดียว ซึ่งเหมาะกว่า pure-GPU cloud

**[[MSFT]]** ได้ประโยชน์จาก Copilot agent ecosystem ที่ built on Azure และ OpenAI partnership ที่ทำให้ทุก breakthrough ใหม่ของ OpenAI แปลงเป็น Azure revenue

**[[GOOGL]]** มี Gemini agent ecosystem และ GCP backlog $460B ส่วนใหญ่มาจาก agentic workload commitments

**[[PLTR]]** (Palantir) คือบริษัทที่มี enterprise agentic revenue ใน production แล้วตอนนี้ ไม่ใช่แค่ planning ผ่าน AIP (Artificial Intelligence Platform) ที่ deploy ใน government และ enterprise clients

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัท enterprise software ที่ขาย "AI features" แต่ยังเป็น human-in-the-loop ทุก step จะถูก disrupt โดย agentic alternatives ที่ทำงานได้เองหลายชั่วโมง โดยเฉพาะในงาน back-office, data entry, customer service, และ code review ที่ agentic AI สามารถทำได้แล้วในปี 2026

ServiceNow เป็นตัวอย่างของ "AI hockey stick ที่ถูก push out" รายได้จาก AI ที่คาดว่าจะเกิดใน 2026 ถูก push ไปปี 2027 ซึ่งแสดงว่า enterprise adoption มีความล่าช้าจาก compliance และ security requirements

## มุมมองระยะยาว

Agentic AI คือ thesis ที่ผูกทุก trend อื่นในรายงานชุดนี้เข้าด้วยกัน เหตุผลที่ memory LTA ต่างจาก cycle เก่า เหตุผลที่ cloud CapEx โต 77% YoY เหตุผลที่ optical คือ bottleneck ถัดไปหลัง GPU ทั้งหมดนี้มีรากในการเปลี่ยนผ่านสู่ agentic AI

Timeline ที่ควรติดตาม: enterprise agentic deployment กว้างขวางขึ้นในปี 2026-2027, AGI ระดับ white-collar ปี 2027-2028 สิ่งที่จะทำให้ thesis ช้าคือ regulatory constraints บน autonomous agent execution และ enterprise compliance ที่ต้องการ human-in-the-loop สำหรับ high-stakes decisions แต่ direction ไม่เปลี่ยน เฉพาะ speed เท่านั้น
`
  },
  {
    tag: "Advanced-Packaging",
    title: "Advanced Packaging: ศิลปะแห่งการประกอบชิปในยุค AI",
    subtitle: "เมื่อ Moore's Law ชะลอตัว วิธีที่ชิปถูก \"แพ็ค\" เข้าด้วยกันกลายเป็น competitive advantage ใหม่",
    conviction: "HIGH",
    last_updated: "2026-07-26",
    summary: "หลายทศวรรษที่ผ่านมา อุตสาหกรรม semiconductor พัฒนาด้วยการทำ transistor ให้เล็กลงทุกสองปีตาม Moore's Law แต่ขณะนี้การทำ transistor ให้เล็กกว่า 2nm กำลังเข้าสู่ข้อจำกัดทางฟิสิกส์ที่แก้ยากมากขึ้นเรื่อยๆ",
    tickers: ["NVDA", "AVGO", "ASML", "INTC"],
    content: `# Advanced Packaging: ศิลปะแห่งการประกอบชิปในยุค AI
*เมื่อ Moore's Law ชะลอตัว วิธีที่ชิปถูก "แพ็ค" เข้าด้วยกันกลายเป็น competitive advantage ใหม่*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-07-26

---

## ภาพรวม — Trend นี้คืออะไร

หลายทศวรรษที่ผ่านมา อุตสาหกรรม semiconductor พัฒนาด้วยการทำ transistor ให้เล็กลงทุกสองปีตาม Moore's Law แต่ขณะนี้การทำ transistor ให้เล็กกว่า 2nm กำลังเข้าสู่ข้อจำกัดทางฟิสิกส์ที่แก้ยากมากขึ้นเรื่อยๆ

ทางออกคือ advanced packaging หรือการนำชิปหลายชิ้นมา "stack" หรือ "connect" เข้าด้วยกันในแพ็คเกจเดียว แทนที่จะพยายามใส่ทุกอย่างในชิปเดียว วิธีนี้เรียกว่า chiplet architecture ซึ่งช่วยให้นักออกแบบสามารถเลือก process ที่ดีที่สุดสำหรับแต่ละส่วนของชิปได้ เช่น CPU core ใช้ node ที่เร็วที่สุด, memory controller ใช้ node อีกแบบ, I/O interface ใช้ node ที่ cost-efficient กว่า แล้วนำมารวมกันในแพ็คเกจเดียวที่ทำงานเสมือนชิปเดียว

TSMC CoWoS (Chip on Wafer on Substrate) คือเทคโนโลยีที่ dominant ที่สุดในปัจจุบัน GPU ทุกตัวของ NVIDIA ทุก accelerator ของ AMD และ ASIC ของ Broadcom ล้วนใช้ CoWoS ปัญหาคือ capacity ยังตึงมาก TSMC ยืนยันว่า CoWoS/SoIC capacity จะ "remain very tight" ถึงปี 2027 แม้จะลงทุนขยายกำลังการผลิตอย่างหนัก

## ทำไมถึงน่าสนใจตอนนี้

การขาดแคลน CoWoS ไม่ใช่ temporary supply/demand imbalance แต่เป็น structural reality เพราะการสร้าง advanced packaging capacity ใช้เวลาและเงินใกล้เคียงกับการสร้าง leading-edge fab ซึ่งหมายความว่า lead time ยาวและไม่สามารถเร่งได้แม้มีเงิน

Intel กำลังสร้าง EMIB (Embedded Multi-die Interconnect Bridge) ซึ่งเป็น advanced packaging technology ของตัวเอง ข่าวใหญ่คือ NVIDIA กำลัง evaluate Intel EMIB สำหรับ next-generation architecture (ข้อมูล ณ มีนาคม 2026 จาก Intel CFO) CFO ของ Intel ยังระบุว่า "packaging business shaping up to be significantly larger than originally anticipated" ซึ่งแปลว่า Intel เห็น opportunity ใหญ่จากการเป็น alternative ให้ TSMC

Hybrid bonding เป็นเทคโนโลยีถัดไปสำหรับ HBM stacking แทนที่จะใช้ solder bump ที่มีความสูง hybrid bonding ใช้ direct copper-to-copper bonding ซึ่งทำให้ stack ได้ถึง 12-20 ชั้นและลด resistance ลงอย่างมีนัยสำคัญ SK Hynix, Micron, และ Samsung ต่างเร่งพัฒนาเทคโนโลยีนี้เพื่อ HBM generation ถัดไป

OSAT (Outsourced Semiconductor Assembly and Test) ซึ่งคือบริษัทที่รับ die จาก fab มาประกอบและทดสอบก็กำลังกลายเป็น "final bottleneck in AI chips" ตาม research ล่าสุด ตลาดยังไม่ได้ price in ความแตกต่างระหว่าง high-margin OSAT test (EBITDA 40%+) กับ commodity OSAT assembly (EBITDA 10%) ซึ่งเป็น opportunity

## หุ้นที่ได้ประโยชน์

**[[NVDA]]** ได้ประโยชน์จาก CoWoS เป็น primary beneficiary เพราะทุก Blackwell/Rubin GPU ใช้ TSMC CoWoS และการที่ NVIDIA evaluate Intel EMIB เป็น backup แสดงว่า NVIDIA กำลัง secure packaging supply ด้วยหลายทาง

**[[AVGO]]** (Broadcom) custom ASICs ทั้งหมดใช้ CoWoS และ Tomahawk 5 CPO ต้องใช้ advanced co-packaging ในการรวม optics กับ chip ในแพ็คเกจเดียว การขยาย packaging capacity โดยรวมจึงเป็นประโยชน์โดยตรง

**[[ASML]]** EUV lithography ที่ ASML ผลิตเป็นพื้นฐานของ leading-edge node ที่ advanced packaging นำมาเชื่อมต่อ การขยาย N2/A14 ของ TSMC ที่ขับเคลื่อนโดย packaging demand ต้องใช้ EUV tools เพิ่มขึ้น

**[[INTC]]** (Intel) EMIB คือ catalyst ที่สำคัญที่สุดสำหรับ Intel Foundry ถ้า NVIDIA qualify Intel EMIB สำหรับ next-generation architecture มันจะเปลี่ยน revenue trajectory ของ Intel Foundry อย่างมีนัยสำคัญ แม้แต่ partial qualification สำหรับ specific chips จะ meaningful Intel's STCO (System Technology Co-Optimization) ที่เป็น 5-layer simultaneous optimization ก็เป็น moat ที่ deeper กว่า node advantage อื่นๆ

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

ผู้ผลิต legacy packaging แบบ wire bond หรือ flip chip ดั้งเดิมที่ไม่ได้ลงทุนใน advanced packaging technology กำลังเห็น margin compression เพราะ AI workloads ต้องการ advanced packaging ทั้งหมด commodity packaging ยังมีตลาดในสินค้า consumer แต่ margin จะถูกกดดันต่อเนื่อง

ความเสี่ยงที่ใหญ่ที่สุดสำหรับ Intel คือ EMIB ไม่ผ่าน NVIDIA qualification ซึ่งจะทำให้ opportunity สำคัญที่สุดหายไป และ Intel Foundry กลับสู่สถานการณ์เดิมที่ยากลำบาก

**อัพเดท ก.ค. 2026:** ข่าวที่คนในวงการจับตามากที่สุดคือ Google เลือกใช้ Intel EMIB-T แทน TSMC CoWoS สำหรับ TPU รุ่นที่ 9 — ถือเป็นครั้งแรกที่ TSMC เสีย "socket" ขนาดใหญ่ให้คู่แข่งจริงๆ ไม่ใช่แค่ล้นไปให้ทำงานเสริม อย่างไรก็ตาม EMIB-T ยังไม่เคยผลิตจริงในสเกลใหญ่ระดับนี้มาก่อน — yield ที่รายงานอยู่ราว 90% ขณะที่ AI chip แพงๆ ต้องการ yield ระดับ 98-99% จึงจะคุ้ม ไตรมาส 3 ปี 2026 คือจุดตรวจสอบสำคัญ (engineering sample ชุดแรก) ถ้า Intel ทำไม่ได้ ธุรกิจนี้อาจไหลกลับไปหา TSMC เหมือนเดิม — เป็นความเสี่ยงที่ต้องติดตามใกล้ชิด ไม่ใช่ความเสี่ยงที่จบแล้ว

นอกจากนี้ยังมีกระแสข่าวว่า TSMC จะใช้ "กระจก" (glass) เป็นวัสดุหลักใน CoPoS (packaging รุ่นถัดไปหลัง CoWoS) ซึ่งทำให้หุ้นซัพพลายเชนวัสดุกระจกบางตัวราคาพุ่งแรง — แต่จากแหล่งข่าวใกล้ชิด TSMC เจนแรกของ CoPoS (คาดผลิตจริงปี 2029) น่าจะยัง "ไม่ใช้กระจกจริง" เพราะกระจกยังเปราะ แตกง่าย ต้นทุนสูงกว่าวัสดุเดิมถึง 10 เท่า ขณะที่ลูกค้าอย่าง Broadcom ยอมจ่ายเพิ่มแค่ 2 เท่า — ดังนั้นกระแส "glass revolution" ในตลาดหุ้นตอนนี้อาจเร็วเกินไปกว่าความเป็นจริง

## มุมมองระยะยาว

Advanced packaging จะยิ่ง strategic มากขึ้นเรื่อยๆ ตามที่ Moore's Law ชะลอ เพราะมันคือวิธีหลักที่อุตสาหกรรมจะยัง deliver performance improvement ต่อไป ในระยะ 3-5 ปี hybrid bonding จะ replace solder bump สำหรับ HBM, CoWoS จะขยาย capacity และ Intel EMIB จะเป็นตัวชี้ขาดว่า Intel Foundry จะ survive หรือไม่ในตลาด advanced packaging

การลงทุนใน INTC ในจุดนี้คือการ bet ที่ asymmetric: downside คือ Intel ยังคงเป็นบริษัทที่กำลัง transform อย่างช้าๆ upside คือ EMIB qualify สำหรับ NVIDIA และ Intel Foundry กลายเป็น business ที่ re-rate ใหม่ทั้งหมด
`
  },
  {
    tag: "Semiconductor-Equipment",
    title: "Semiconductor Equipment Upcycle: เครื่องจักรที่โลกขาดไม่ได้",
    subtitle: "ASML คือบริษัทเดียวในโลกที่ทำสิ่งนี้ได้ และทุกคนต้องซื้อจากที่นี่เท่านั้น",
    conviction: "HIGH",
    last_updated: "2026-05-16",
    summary: "ในการลงทุน moat ที่แข็งแกร่งที่สุดคือเมื่อลูกค้าไม่มีทางเลือกอื่น ไม่ใช่เพราะ contract ที่ล็อกไว้ แต่เพราะไม่มีใครทำสิ่งที่คุณทำได้",
    tickers: ["ASML"],
    content: `# Semiconductor Equipment Upcycle: เครื่องจักรที่โลกขาดไม่ได้
*ASML คือบริษัทเดียวในโลกที่ทำสิ่งนี้ได้ และทุกคนต้องซื้อจากที่นี่เท่านั้น*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ในการลงทุน moat ที่แข็งแกร่งที่สุดคือเมื่อลูกค้าไม่มีทางเลือกอื่น ไม่ใช่เพราะ contract ที่ล็อกไว้ แต่เพราะไม่มีใครทำสิ่งที่คุณทำได้

ASML คือบริษัทในฝันนั้น เครื่อง EUV (Extreme Ultraviolet) lithography ที่ ASML ผลิตคือเครื่องเดียวในโลกที่สามารถ "พิมพ์" circuit ลงบน semiconductor wafer ด้วยความละเอียดต่ำกว่า 5nm ได้ ไม่มีบริษัทอื่นในโลกที่ทำได้ และจะไม่มีอย่างน้อยอีก 5-7 ปี

ทำไมถึงยากขนาดนี้? เครื่อง EUV ใช้แสงที่มีความยาวคลื่น 13.5 nm ซึ่งดูดซับโดยอากาศ ดังนั้นทุกส่วนของเครื่องต้องทำงานใน vacuum เครื่องแต่ละเครื่องมีชิ้นส่วนจากซัพพลายเออร์ 5,000+ ราย ใช้เวลาผลิต 2-3 ปีต่อเครื่อง และราคาเครื่องละ $350M+ TSMC, Samsung, Intel ต่างต้องซื้อจาก ASML เท่านั้น ไม่มี plan B

## ทำไมถึงน่าสนใจตอนนี้

ASML ปรับคาดการณ์รายได้ปี 2026 ขึ้นเป็น €36-40B (จาก €34-39B เดิม) และบน earnings call Q1 2026 ASML ระบุชัดเจนว่าคาดว่าจะเกิด "EUV supply shortage ในปี 2027" ประโยคนี้ฟังดูเป็นข่าวร้ายสำหรับลูกค้า แต่สำหรับนักลงทุนมันคือข่าวดีมาก เพราะหมายความว่า order book เต็มล้นไปถึงปี 2027 ก่อนที่จะรับ order ใหม่ได้

TSMC ซึ่งเป็นลูกค้าหลักของ ASML กำหนด CapEx ที่ขอบบนของ $52-56B สำหรับปี 2026 และประกาศว่า "CapEx ในสามปีข้างหน้าจะสูงกว่าสามปีที่ผ่านมาอย่างมีนัยสำคัญ" TSMC N2 เข้า mass production แล้วใน Q4 2025, N3 ยังตึงมากถึงปี 2027, A14 (2nm ขั้นถัดไป) อยู่ใน schedule สำหรับ 2028 แต่ละ node ใหม่ต้องการ EUV tools ใหม่หลายสิบเครื่อง

แม้แต่ CXMT ของจีนที่กำลังพยายามสร้าง DRAM capacity ด้วยตัวเองก็ยังต้องการ ASML DUV tools (ไม่ใช่ EUV เพราะถูก restrict) สำหรับ mature node ซึ่งเพิ่ม demand อีกด้านหนึ่ง CXMT กำลังจะทำ $42B IPO และมี capacity 720K wafers/quarter แล้ว

## หุ้นที่ได้ประโยชน์

**[[ASML]]** คือชื่อเดียวใน watchlist ที่อยู่ใน Semiconductor-Equipment trend โดยตรง แต่มันก็เป็นชื่อที่ conviction สูงที่สุด monopoly ที่ true ในอุตสาหกรรมที่ critical ที่สุดในโลก gross margin 53% ที่ scale ไม่ใช่ margin ของบริษัท software แต่คือ margin ของผู้ผูกขาดเครื่องมือที่ขาดไม่ได้

ในมุมมองของ Warren: ASML คือ longest-duration compounder ที่มี lowest execution risk ใน watchlist ทั้งหมด business model ไม่ซับซ้อน ลูกค้าไม่มีทางเลือก demand จาก AI semiconductor buildout จะดำเนินต่อเนื่องตลอดทศวรรษนี้ และ ASML ไม่สามารถผลิตเร็วพอที่จะ satisfy demand

**บริษัทที่ได้ประโยชน์ทางอ้อม** ได้แก่ TSMC, NVDA, AVGO, MRVL ที่ล้วนต้องการให้ ASML ผลิต EUV tools ได้เพียงพอเพื่อที่จะขยาย capacity ของตัวเองได้ ดังนั้นทุกคนใน AI semiconductor value chain มี interest ร่วมกันที่ต้องการให้ ASML healthy

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

ความเสี่ยงที่ใหญ่ที่สุดสำหรับ ASML คือ China exposure ASML ยังขาย DUV (ไม่ใช่ EUV) ให้จีนได้ และ China คิดเป็น ~25-30% ของรายได้รวม ถ้าสหรัฐอเมริกาบังคับให้ ASML หยุดขาย DUV ให้จีนด้วย (ตอนนี้เฉพาะ LUVHC ที่ถูก restrict) จะกระทบรายได้ส่วนนี้อย่างมีนัยสำคัญในระยะสั้น เพราะจะ redirect ไปยังลูกค้าอื่นได้ยากทันที

นักลงทุนที่มองว่า semiconductor equipment cycle จะ peak ใน 2026-2027 และ cut position อาจพลาด เพราะ AI-driven buildout แตกต่างจาก PC/smartphone cycle ก่อนหน้านี้ตรงที่ไม่มี demand ceiling ที่ชัดเจน ตราบใดที่ AI adoption ยังเติบโต

## มุมมองระยะยาว

ASML ไม่ใช่ cyclical story แต่เป็น secular compounder ที่มีทัศนวิสัยชัดเจน roadmap ของ TSMC ที่ extend ไปถึง A14 (2028) และ beyond แปลว่า ASML จะมี order visibility หลายปีล่วงหน้าเสมอ

ในระยะ 5 ปี High-NA EUV (รุ่นถัดไปหลัง EUV ปัจจุบัน) จะเริ่ม ramp ซึ่ง ASML ก็เป็น sole supplier เช่นกัน นั่นหมายความว่า moat ไม่ได้แค่ defend ได้ แต่ยังขยายตัวได้ด้วย ราคาต่อเครื่องที่สูงกว่า EUV ปัจจุบัน 2-3x ในระยะยาว
`
  },
  {
    tag: "CPU-Renaissance",
    title: "CPU Renaissance: การฟื้นคืนชีพของชิปที่ทุกคนลืม",
    subtitle: "ทุกคนจ้องที่ GPU แต่ agentic AI กำลังทำให้ CPU กลับมามีความสำคัญอีกครั้ง",
    conviction: "HIGH",
    last_updated: "2026-07-27",
    summary: "ตั้งแต่ปี 2022 เป็นต้นมา ทุกบทสนทนาเรื่อง AI semiconductor มักวนเวียนอยู่กับ GPU GPU ใหญ่กว่า เร็วกว่า มี HBM มากกว่า NVIDIA คืนใหม่ที่สาย semiconductor รอคอย CPU ที่เคยเป็นหัวใจของ computing กลายเป็นเพียงผู้สนับสนุนที่ไม่มีใครพูดถึง",
    tickers: ["ARM", "INTC", "AMD"],
    content: `# CPU Renaissance: การฟื้นคืนชีพของชิปที่ทุกคนลืม
*ทุกคนจ้องที่ GPU แต่ agentic AI กำลังทำให้ CPU กลับมามีความสำคัญอีกครั้ง*

**Warren's Conviction:** HIGH
**Last Updated:** 2026-07-27
*(ปรับขึ้นจาก MED เมื่อ 2026-07-27 — ดูรายละเอียดในหัวข้อ "อัพเดท 2026-07-27" ด้านล่าง)*

---

## ภาพรวม — Trend นี้คืออะไร

ตั้งแต่ปี 2022 เป็นต้นมา ทุกบทสนทนาเรื่อง AI semiconductor มักวนเวียนอยู่กับ GPU GPU ใหญ่กว่า เร็วกว่า มี HBM มากกว่า NVIDIA คืนใหม่ที่สาย semiconductor รอคอย CPU ที่เคยเป็นหัวใจของ computing กลายเป็นเพียงผู้สนับสนุนที่ไม่มีใครพูดถึง

แต่ agentic AI กำลังเปลี่ยนสมการนี้

ใน AI training แบบดั้งเดิม ratio ของ GPU ต่อ CPU อยู่ที่ 8:1 เพราะงาน training ต้องการ parallel computation มหาศาล ใน inference งาน ratio ลดลงมาที่ 3-4:1 แต่ใน agentic AI ที่ AI ต้อง orchestrate tools, เรียก API, อ่านฐานข้อมูล, ส่ง email, และตัดสินใจใน multi-step workflows ratio อาจ tighten มาสู่ 1:1 หรือสูงกว่า เพราะงาน orchestration และ control plane ทั้งหมดนี้ใช้ CPU ไม่ใช่ GPU

วันที่ 24 เมษายน 2026 Intel CEO Lip-Bu Tan กล่าวในงาน earnings call ว่า "The CPU is reasserting itself as the indispensable foundation of the AI era" หุ้น Intel ขึ้น +24% ในวันเดียว ซึ่งเป็น biggest single-day gain ของ Intel ตั้งแต่ปี 1987 ดึง AMD +14%, ARM +14%, Qualcomm +11% ขึ้นมาด้วย

## ทำไมถึงน่าสนใจตอนนี้

Intel Q1 2026 มีตัวเลขที่ดีกว่าคาดอย่างมีนัยสำคัญ: revenue $13.6B, non-GAAP EPS $0.29 เทียบกับ consensus ที่คาดเพียง $0.01 data center revenue $5.1B (+22% YoY) ตัวเลข EPS ที่เกิน consensus แบบนี้แสดงว่าการฟื้นตัวของ server CPU demand ดีกว่าที่ Street model ไว้มาก

Intel capacity reallocation strategy กำลัง work: การย้าย 10% ของ PC wafer capacity สามารถ support การ growth ของ server shipment 20%+ เพราะ server die มีขนาดใหญ่กว่าและ complex กว่า margin จาก server CPU สูงกว่า PC มาก

AWS Graviton ซึ่งเป็น ARM-based CPU ที่ Amazon ออกแบบเองนั้นได้รับความไว้วางใจจาก 98% ของ top 1,000 EC2 customers และมีประสิทธิภาพดีกว่า x86 equivalent 40% ในแง่ price/performance Meta ยังประกาศ commit tens of millions ของ Graviton cores ซึ่งเป็น validation จากบริษัทที่ไม่ได้อยู่ใน Amazon ecosystem

Philadelphia SOX index ทะลุ 10,000 เป็นครั้งแรกในวันเดียวกับที่ Intel ประกาศผลประกอบการ ซึ่งแสดงว่า market กำลัง re-rate semiconductor sector ทั้งหมดบนพื้นฐานของ CPU comeback story

## หุ้นที่ได้ประโยชน์

**[[ARM]]** คือ highest-conviction play ใน CPU Renaissance ARM ผลิต ISA (Instruction Set Architecture) ที่ทุก ARM-based CPU ต้องใช้ license ไม่ว่าจะเป็น Apple M-series, AWS Graviton, Qualcomm Snapdragon, หรือ Nvidia Grace CPU ARM ได้ royalty จากทุกชิปที่ขาย win condition ของ ARM ง่ายมาก: "ARM architecture proliferates in servers" ไม่ว่า Intel หรือ AMD จะชนะ ไม่ว่า Apple หรือ Qualcomm จะแข็งแกร่งกว่ากัน ARM ชนะเสมอถ้า ARM ISA ขยายตัว

**[[INTC]]** (Intel) มีหลายปัจจัย: server demand ดีกว่าคาด, capacity reallocation ทำงาน, EMIB packaging optionality, STCO framework ที่เป็น deeper moat กว่าที่ตลาดเข้าใจ แต่ conviction อยู่ที่ MED เพราะ thesis ขึ้นอยู่กับหลายเงื่อนไขพร้อมกัน

**[[AMD]]** EPYC server CPU กำลังได้ market share จาก Intel ใน enterprise server Zen 6 Venice ออกแบบสำหรับ agentic orchestration โดยเฉพาะ MI300X ที่รวม CPU+GPU ในแพ็คเกจเดียวก็ทำให้ AMD ได้ประโยชน์จากทั้ง CPU และ GPU side พร้อมกัน

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

ความเสี่ยงที่ใหญ่ที่สุดสำหรับทั้ง Intel และ AMD คือ hyperscalers ที่กำลังพัฒนา RISC-V CPU ของตัวเอง Google, Amazon, Meta ต่างมี program ในการ explore custom CPU architectures ที่ bypass Intel/AMD/ARM royalties ถ้าเส้นทางนี้เร็วกว่าที่คาด จะ compress TAM ของ CPU สำเร็จรูปในระยะ 5-7 ปี

Intel ยังมีความเสี่ยงว่า Q1 2026 อาจเป็นผลของ inventory restocking หลัง trough ไม่ใช่ structural demand recovery จริง Q2 2026 จะเป็น test สำคัญที่จะตอบคำถามนี้

## อัพเดท 2026-07-27 — ปรับ Conviction ขึ้นเป็น HIGH

ธนาคารสองแห่ง (BofA และ UBS) ยืนยันตรงกันโดยอิสระว่าตลาด server CPU กำลังขยายตัวใหญ่กว่าที่เคยประเมินไว้มาก BofA ปรับเป้า CY2030 server CPU TAM จาก $125bn เป็น **$170bn+** (โต ~5 เท่า, CAGR 37%) แบ่งเป็น traditional CPU $30bn + AI head-node CPU $70bn + AI agentic-standalone CPU $70bn ส่วน UBS จากงาน Computex รายงานว่าวงการกำลังพูดถึงตัวเลขที่สูงกว่านั้นอีกที่ **~$200bn+**

จุดที่น่าสนใจที่สุดคือ ARM: แม้ BofA จะปรับเป้าราคาขึ้นจาก $245 เป็น $335 (คิดจาก sum-of-parts ธุรกิจ IP + ธุรกิจชิป) และเห็นว่า ARM จะได้ market share รวมของ server CPU สูงถึง ~50% ภายในปี 2030 (35% จากชิป merchant + 15% จาก custom ASIC ของ hyperscaler) แต่ BofA ยังคงเรตติ้ง ARM ไว้ที่ **Neutral — "ราคาเหมาะสมแล้ว"** เท่านั้น สะท้อนว่าตลาดได้ price-in โอกาสเติบโตนี้ไปมากแล้ว

NVIDIA เปิดเผยว่า Vera CPU จะมียอดขาย ~$20bn ในช่วงครึ่งหลังปี 2027 แบ่งเท่าๆ กันระหว่างงาน head-node กับ agentic-standalone และ content ต่อ GW ของ NVIDIA เพิ่มขึ้นทุกเจนเนอเรชัน จาก ~$40bn/GW (Blackwell Ultra) เป็น $60-80bn/GW (Vera Rubin) และอาจถึง ~$100bn/GW (Feynman ปี 2028)

## มุมมองระยะยาว

CPU Renaissance ไม่ได้หมายความว่า CPU จะ "แซง" GPU ในโลก AI มันหมายความว่า CPU จะกลับมามีความสำคัญในระดับที่ใกล้เคียง GPU ใน agentic workloads ซึ่งเป็นเรื่องของ mix shift ไม่ใช่ winner-take-all

ARM มีโอกาสสูงที่สุดที่จะ compound ได้ดีที่สุดใน 3-5 ปี เพราะ royalty model ไม่ sensitive กับ execution risk เดียวกับที่ Intel ต้องเผชิญ ในขณะที่ Intel story น่าสนใจ ต้องรอดูว่า Q2 และ Q3 2026 จะยืนยัน structural recovery หรือไม่ก่อนที่จะเพิ่ม conviction
`
  },
  {
    tag: "Power-Infrastructure",
    title: "Power Infrastructure: ไฟฟ้าที่โลก AI ต้องการ",
    subtitle: "ทุกคนพูดถึง GPU และ memory แต่ AI datacenter ไม่มีทางทำงานได้โดยไม่มีไฟฟ้า",
    conviction: "MED",
    last_updated: "2026-05-16",
    summary: "ลองนึกถึงการสร้างเมืองขนาดใหญ่ใหม่ ทุกคนตื่นเต้นกับ high-rise buildings และ shopping malls แต่ถ้าระบบไฟฟ้าและน้ำประปาไม่พร้อม ตึกสวยๆ ก็ใช้ไม่ได้ AI datacenter คือสถานการณ์เดียวกัน",
    tickers: ["VRT"],
    content: `# Power Infrastructure: ไฟฟ้าที่โลก AI ต้องการ
*ทุกคนพูดถึง GPU และ memory แต่ AI datacenter ไม่มีทางทำงานได้โดยไม่มีไฟฟ้า*

**Warren's Conviction:** MED
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ลองนึกถึงการสร้างเมืองขนาดใหญ่ใหม่ ทุกคนตื่นเต้นกับ high-rise buildings และ shopping malls แต่ถ้าระบบไฟฟ้าและน้ำประปาไม่พร้อม ตึกสวยๆ ก็ใช้ไม่ได้ AI datacenter คือสถานการณ์เดียวกัน

ความต้องการพลังงานไฟฟ้าของ datacenter ทั่วโลกกำลังเพิ่มจาก ~59GW ในปี 2023 ไปสู่ 122GW+ ในปี 2030 นั่นคือการเพิ่ม 63GW ในเจ็ดปี ซึ่งเท่ากับการใช้ไฟฟ้าทั้งหมดของประเทศฝรั่งเศส

แต่ "power infrastructure" ไม่ใช่แค่ grid ไฟฟ้า มันคือ chain ยาว 10 ขั้นตอนตั้งแต่โรงไฟฟ้า (765kV) ลงมาจนถึง GPU die (0.65V) แต่ละขั้นตอนมี bottleneck ของตัวเอง: transformer ที่ใช้เวลาผลิต 2-3 ปี, grid interconnection ที่ต้องรอ 4-7 ปีใน Northern Virginia (ตลาด datacenter ใหญ่สุดของสหรัฐ), UPS และ cooling system ที่ต้องอัปเกรดเพราะ GPU รุ่นใหม่ใช้ไฟมากกว่าเดิมมาก

## ทำไมถึงน่าสนใจตอนนี้

GPU รุ่นใหม่ใช้ไฟมากขึ้นอย่างมากและรวดเร็ว ไม่นานมานี้ GPU rack ใช้ไฟ 10-20 kW แต่ rack ที่ติดตั้ง NVIDIA Blackwell ปัจจุบันใช้ถึง 100-200 kW และจะเพิ่มขึ้นต่อไปอีกตาม GPU รุ่นถัดๆ ไป การที่ power density เพิ่มขึ้น 10x นี้หมายความว่า cooling และ power distribution systems ทั้งหมดใน datacenter ที่มีอยู่ต้องอัปเกรดหรือ replace

Vertiv Q1 2026 revenue $2.65B (+30% YoY) มี order backlog ~$9.5B และ FY2026 guidance $13.5-14.0B Eaton datacenter orders เพิ่มขึ้น +240% YoY, datacenter revenue +50%, backlog $22.8B GE Vernova ได้ datacenter Electrification orders $2.4B ใน Q1 2026 เพียงไตรมาสเดียว ซึ่งเกินกว่า FY2025 ทั้งปีรวมกัน

AWS เพิ่ม power capacity ใหม่ 3.9 gigawatts ในปี 2025 และคาดว่าจะ double total power capacity ภายในสิ้นปี 2027 ตัวเลขนี้แสดงว่า hyperscalers กำลัง treat power infrastructure เหมือน strategic asset ไม่ใช่แค่ utility cost

NVIDIA ประกาศ 800V DC power architecture ecosystem ที่รวม ABB, Eaton, Schneider, Vertiv, Infineon, STM, Navitas ซึ่งเป็นการ standardize power architecture ระดับ industry ที่จะ benefit บริษัทที่ certified กับ standard ใหม่นี้

## หุ้นที่ได้ประโยชน์

**[[VRT]]** (Vertiv) คือชื่อเดียวใน watchlist ที่ครอบคลุมทั้ง power AND cooling พร้อมกัน บริษัทอื่นอาจทำ power หรือ cooling แต่ไม่ครบทั้งสองอย่าง ใน ecosystem ที่ power density เพิ่มขึ้น liquid cooling กลายเป็น mandatory (ไม่ใช่ optional) สำหรับ GPU TDP 1,400W+ และ Vertiv's integrated stack capture ทั้งส่วน power และ cooling ซึ่งขายร่วมกันได้ในสัญญาเดียว

backlog $9.5B ของ Vertiv ให้ revenue visibility 6-8 ไตรมาสล่วงหน้า ซึ่งสูงกว่าบริษัทส่วนใหญ่ในตลาด ทำให้ risk ของการ miss guidance ต่ำกว่าปกติ

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัท co-location datacenter ที่ยังใช้ air cooling แบบเก่าและไม่ได้เตรียม infrastructure สำหรับ liquid cooling จะเสียลูกค้าไปยัง purpose-built AI datacenter ที่มี infrastructure พร้อม ในระยะ 2-3 ปี co-location แบบดั้งเดิมจะไม่สามารถรองรับ high-density AI workload ได้อีกต่อไป

Eaton ซื้อ Boyd Thermal ด้วยมูลค่า $9.5B เพื่อเข้าสู่ cooling market ซึ่งจะ compete กับ Vertiv โดยตรง ถ้า Eaton integrate ได้ดีและ price อย่าง aggressive อาจกดดัน margin ของ Vertiv ใน 2026-2027

## มุมมองระยะยาว

Power infrastructure เป็น bottleneck ที่มี lead time ยาวที่สุดและแก้ยากที่สุดใน AI datacenter buildout ไม่ใช่ GPU ไม่ใช่ memory grid interconnection queue ที่ 4-7 ปีใน Northern Virginia คือ physical constraint ที่ไม่สามารถแก้ได้ด้วยเงิน ไม่ว่า Big Tech จะทุ่มเงินเท่าไร

ในระยะ 3-5 ปี NVIDIA 800V DC architecture จะ become standard และบริษัทที่อยู่ใน certified ecosystem จะได้ประโยชน์จาก pricing power ที่มากขึ้น สิ่งที่จะเปลี่ยน thesis คือ breakthrough ใน grid permitting ที่ลด lead time จาก 4-7 ปีลงมาอย่างมีนัยสำคัญ ซึ่งตอนนี้ยังไม่มีสัญญาณว่าจะเกิดขึ้นเร็วๆ นี้
`
  },
  {
    tag: "Humanoid-Robots",
    title: "Humanoid Robots: AI ก้าวออกจากจอคอมพิวเตอร์",
    subtitle: "ราคาหุ่นยนต์ลดลง 97% ในสองปี นี่คือสัญญาณของการเปลี่ยนแปลงที่ไม่ใช่แค่ trend",
    conviction: "MED",
    last_updated: "2026-05-16",
    summary: "ตลอดประวัติศาสตร์ เมื่อราคาของเทคโนโลยีลดลงอย่างรวดเร็วและต่อเนื่อง มันมักนำมาซึ่งการ adoption ที่เปลี่ยนโลก เราเห็นสิ่งนี้กับ smartphone ที่ราคาลดลงจนคนทั่วโลกมีกัน เราเห็นกับ solar panel ที่ถูกกว่าถ่านหินในปัจจุบัน และตอนนี้เราอาจกำลังเห็นสิ่งเดียวกันกับ humanoid robots",
    tickers: ["TSLA", "NVDA"],
    content: `# Humanoid Robots: AI ก้าวออกจากจอคอมพิวเตอร์
*ราคาหุ่นยนต์ลดลง 97% ในสองปี นี่คือสัญญาณของการเปลี่ยนแปลงที่ไม่ใช่แค่ trend*

**Warren's Conviction:** MED
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ตลอดประวัติศาสตร์ เมื่อราคาของเทคโนโลยีลดลงอย่างรวดเร็วและต่อเนื่อง มันมักนำมาซึ่งการ adoption ที่เปลี่ยนโลก เราเห็นสิ่งนี้กับ smartphone ที่ราคาลดลงจนคนทั่วโลกมีกัน เราเห็นกับ solar panel ที่ถูกกว่าถ่านหินในปัจจุบัน และตอนนี้เราอาจกำลังเห็นสิ่งเดียวกันกับ humanoid robots

หุ่นยนต์ industrial ดั้งเดิมในปี 2023 มีราคาอยู่ที่ $500,000 ต่อตัว Unitree G-1 ในปี 2025 ราคา $16,000 นั่นคือการลดลง 97% ในสองปี ถ้าแนวโน้มนี้ยังดำเนินต่อไปในอัตราใกล้เคียงกัน ในปี 2028-2030 หุ่นยนต์ที่ทำงานได้จริงในโกดังหรือโรงงานอาจมีราคาถูกกว่าค่าแรงมนุษย์ในหลายประเทศ

สิ่งที่ทำให้ปี 2026 แตกต่างจากรอบก่อนๆ ที่ humanoid robot เคย "จะมา" แต่ไม่มา คือ teleoperation model ที่ทำให้ ROI เป็นบวกได้โดยไม่ต้องรอ full autonomy คนคนหนึ่งในอินเดียสามารถ supervise หุ่นยนต์ 4-5 ตัวในสหรัฐอเมริกาพร้อมกันได้ ณ ค่าแรงที่แตกต่างกันหลายเท่า ทำให้ economics work ได้แม้หุ่นยนต์ยังไม่สมบูรณ์

## ทำไมถึงน่าสนใจตอนนี้

Amazon กำลัง implement หุ่นยนต์ Digit ของ Agility Robotics ใน warehouse จริงแล้ว GXO Logistics และ Apptronik กำลัง pilot pick-and-place robots มากกว่าหนึ่งปีแล้ว Tesla Optimus กำลัง develop ด้วย vertically integrated manufacturing ที่เป็น cost advantage ที่สุดในอุตสาหกรรม

NVIDIA Isaac และ Omniverse ซึ่งเป็น platform สำหรับ robot training ทำให้ company สามารถ train หุ่นยนต์ใน simulation ก่อนที่จะ deploy จริง ซึ่งลด cost และเวลาของการ training ลงอย่างมาก นี่คือ enabler ที่ทำให้ barrier to entry ของ robotics ลดลงสำหรับทุกคน ไม่ใช่แค่ Tesla หรือ Amazon

cycle ใน auto/industrial sector กำลังส่งสัญญาณว่า downtrend ถึงจุด bottom แล้ว comments จาก RRX, MCHP, ON, IFX ใน earnings calls ล่าสุดแสดงว่า inventory correction ใกล้สิ้นสุด ซึ่งเป็น setup ที่ดีสำหรับการซื้อ exposure ก่อนที่ cycle จะ turn

## หุ้นที่ได้ประโยชน์

**[[TSLA]]** (Tesla) มี Optimus robot ที่อยู่ระหว่างพัฒนา ข้อได้เปรียบหลักของ Tesla คือ vertically integrated manufacturing — Tesla ผลิตชิ้นส่วนสำคัญเองทำให้ cost per robot ต่ำกว่าผู้ผลิตอื่นที่ซื้อ component จากภายนอก นอกจากนี้ Tesla ยังมี partnership กับ NVIDIA สำหรับ robot training compute ซึ่งลด R&D cost การได้ประโยชน์จาก Optimus ยังไม่แน่นอนว่าจะเกิดขึ้นเมื่อไร แต่ถ้าเกิดขึ้นก็จะเป็น transformative อย่างมาก

**[[NVDA]]** ได้ประโยชน์ในฐานะ primary compute platform สำหรับ robot training และ simulation ผ่าน Omniverse/Isaac robotics training เป็น growing revenue line ให้ NVIDIA แม้ตอนนี้ยังไม่ material เทียบกับ datacenter แต่จะโตขึ้นเรื่อยๆ ตาม adoption ของ humanoid robots

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

บริษัทที่ใช้ low-skill labor จำนวนมากในสภาพแวดล้อม structured เช่น e-commerce warehouse, food processing, และ simple assembly lines เผชิญกับความเสี่ยงระยะยาวจาก humanoid robots ในเวลา 5-10 ปีข้างหน้า

ผู้ผลิต industrial robot แบบ traditional ที่ไม่ได้ design สำหรับ AI training pipeline จะเสียตลาดให้กับ AI-native robot companies เพราะ robot ที่ train ด้วย NVIDIA Omniverse จะ learn faster และ adapt ได้ดีกว่า

ผู้ผลิต hardware component จีนอย่าง Unitree อาจ commoditize hardware layer ก่อนที่ตะวันตกจะ establish software moat ซึ่งเป็น risk ที่ต้องติดตาม

## มุมมองระยะยาว

Humanoid robotics คือ theme ที่ตื่นเต้นที่สุดในรายการทั้งหมด แต่เป็น theme ที่เล่นยากที่สุดผ่าน watchlist ปัจจุบัน pure-play ที่ดีที่สุดอย่าง Agility Robotics, Figure AI, 1X Technologies ยังไม่ได้ IPO exposure ที่มีคือผ่าน TSLA (Optimus, uncertain) และ NVDA (training compute, supporting role)

ใน 3-5 ปีข้างหน้า humanoid robots จะ deploy ใน warehouse และ controlled environment ก่อน ตามด้วยการขยายไปยัง semi-structured environment ใน 5-10 ปี ก่อนที่ unstructured real-world deployment จะเป็นไปได้ในเชิง commercial ขนาดใหญ่ นักลงทุนที่ต้องการ exposure ตอนนี้ควร size position ให้สะท้อน timeline uncertainty ที่ยาวนานนี้
`
  },
  {
    tag: "Space-Defense",
    title: "Space & Defense: จากจรวดสู่เลเซอร์ทำลายล้าง",
    subtitle: "SpaceX IPO มูลค่า $1.75T และอาวุธพลังงานทิศทาง (DEW) กลายเป็นจริงพร้อมกันในปี 2026",
    conviction: "MED",
    last_updated: "2026-05-25",
    summary: "Space และ Defense กำลังผ่านจุดเปลี่ยนพร้อมกันสองด้าน ด้านแรกคือ Space ที่เคยเป็น \"artisan prestige engineering\" ราคาหลายพันล้านดอลลาร์ กำลังกลายเป็นอุตสาหกรรมสายพานผลิต ต้นทุนขนส่งสู่วงโคจรลดลง 95%+ จาก $54,000/kg ของ Space Shuttle เหลือ <$2,000/kg ของ Falcon 9 และกำลังมุ่งสู่ <$200/kg เมื่อ Starship V3 สำเร็จ",
    tickers: ["LASR", "ASTS", "PL", "RDW", "STM"],
    content: `# Space & Defense: จากจรวดสู่เลเซอร์ทำลายล้าง
*SpaceX IPO มูลค่า $1.75T และอาวุธพลังงานทิศทาง (DEW) กลายเป็นจริงพร้อมกันในปี 2026*

**Warren's Conviction:** MED
**Last Updated:** 2026-05-25

---

## ภาพรวม — Trend นี้คืออะไร

Space และ Defense กำลังผ่านจุดเปลี่ยนพร้อมกันสองด้าน ด้านแรกคือ Space ที่เคยเป็น "artisan prestige engineering" ราคาหลายพันล้านดอลลาร์ กำลังกลายเป็นอุตสาหกรรมสายพานผลิต ต้นทุนขนส่งสู่วงโคจรลดลง 95%+ จาก $54,000/kg ของ Space Shuttle เหลือ <$2,000/kg ของ Falcon 9 และกำลังมุ่งสู่ <$200/kg เมื่อ Starship V3 สำเร็จ

ด้านที่สอง ใน 3 เดือนระหว่างพฤศจิกายน 2025 ถึงมกราคม 2026 อาวุธ Directed Energy (DEW) ที่ล้มเหลวมา 40 ปีกลายเป็นจริง UK DragonFire ยิงโดรนที่บิน 400 mph ตก, ระบบ Iron Beam ของอิสราเอลกลายเป็น laser air defense ระบบแรกในประวัติศาสตร์ที่ใช้งานได้จริง, สหรัฐฯ จัดงบ Golden Dome $13B ในปีงบประมาณ 2026 เพียงปีเดียว

เหตุผลที่ economics เปลี่ยน: ค่าใช้จ่ายต่อการสกัดกั้นหนึ่งครั้งของ Iron Dome = $50,000 ค่าใช้จ่ายของ Iron Beam = ราคา electricity ไม่กี่ดอลลาร์ เมื่ออิหร่านยิงขีปนาวุธหลายร้อยลูกพร้อมกัน ระบบ missile interceptor สามารถหมดกระสุนได้ แต่ laser ไม่มีวันหมด

## จุดเปลี่ยนสำคัญ: SpaceX IPO (SPCX)

SpaceX กำลัง IPO ในวันที่ 12 มิถุนายน 2026 บน Nasdaq ด้วย ticker **SPCX** มูลค่าเป้าหมาย $1.75T และระดมทุน $75B ซึ่งเป็น IPO ที่ใหญ่ที่สุดในประวัติศาสตร์ นี่คือครั้งแรกที่นักลงทุนสาธารณะจะสามารถถือหุ้นใน orbital economy ได้โดยตรง

โครงสร้าง 4 เสาของ SpaceX (หลังการซื้อกิจการ xAI ในเดือนกุมภาพันธ์ 2026):
- **Starlink**: รายได้ subscription $12B ต่อปี, 10M+ subscribers ใน 100+ ประเทศ
- **Launch Services**: ~80% ของ mass ที่ขึ้นสู่วงโคจรในสหรัฐฯ, Falcon 9 launch ทุก 3 วัน
- **Starshield**: ภาครัฐและกองทัพ (segment ที่เติบโตเร็วที่สุด)
- **Space Computing**: Orbital Data Centers + xAI — เป้าหมาย AI compute 100 GW-class บนวงโคจร

Flywheel ของ SpaceX: Falcon 9 launch Starlinks → subscription revenue → fund Starship → Starship ทำให้ cost/kg <$200 → deploy Starlink V3 (1 Tbps/satellite) + Orbital Data Centers → xAI เป็น anchor compute tenant

## หุ้นที่ได้ประโยชน์

**[[LASR]]** (nLight) คือ pure-play DEW integrator เพียงรายเดียวที่ listed ในตลาด เป็นผู้ผลิตและ integrator ที่ทำ "everything in the system" — ได้รับการยืนยันว่าเป็น supplier ให้กับ Iron Beam, Pentagon HELSI megawatt program, และ Golden Dome RFP Citrini เข้าซื้อที่ $8.47 ในเดือนพฤษภาคม 2025 และ 6x แล้ว แต่ thesis ของ structural growth เพิ่งเริ่มต้น — US Navy ตั้งใจจะติด laser ใน "ทุกเรือ" ซึ่งมีอยู่ ~290 ลำ

**[[ASTS]]** (AST SpaceMobile) เทคโนโลยี Direct-to-Cell ให้ smartphone ต่อตรงกับดาวเทียมโดยไม่ต้องมี dedicated terminal Q4 2025 รายได้ $54.3M (beat consensus 30%), service revenue $18.1M ที่ margin 87.9%, liquidity $4B ลดความเสี่ยง dilution เป้าหมาย: 45-60 ดาวเทียมภายในสิ้นปี 2026

**[[PL]]** (Planet Labs) เพิ่งบรรลุ positive FCF เป็นครั้งแรกในประวัติศาสตร์ มี backlog $900M และ D&I revenue +50% YoY จาก Swedish Armed Forces, DIU INDOPACOM, NATO กำลังเปลี่ยน business model จาก data subscription ไปสู่ Satellite-as-a-Service ซึ่ง TAM ใหญ่กว่า 6-10x

**[[RDW]]** (Redwire) Q1 2026: book-to-bill 1.92x, backlog สูงสุดตลอดกาล $498M pipeline ที่น่าสนใจ: Andromeda program (~$6B), Golden Dome (VLEO prime), Lunar Power Grid ใกล้ชิดกว่าผู้เล่นอื่น

**[[STM]]** (STMicroelectronics) เป็น officially confirmed RF supplier ให้ SpaceX มี cumulative revenue เป้าหมาย $3B ปี 2026-2028 ความเสี่ยง: SpaceX กำลัง insource packaging ที่ Bastrop TX ปลายปี 2026

## มุมมองระยะยาว

Space-Defense มีสองเรื่องที่น่าสนใจในมิติที่แตกต่างกัน

**DEW เป็น thesis ที่ยืนยันแล้ว** Iron Beam ใช้งานได้จริง Golden Dome มีงบจัดสรรแล้ว สิ่งที่เหลือคือ scale contracts และ deployment LASR ขึ้น 6x แล้วแต่ structural story ยังอยู่ในช่วงต้น

**Commercial space** ทั้ง ASTS, PL, RDW กำลังเปลี่ยนจาก concept เป็น commercial — PL de-risked ที่สุด, ASTS มี ceiling สูงสุด, RDW มี dilution risk ระยะสั้นจาก ATM offering

**SPCX IPO** คือ catalyst สำคัญ — ก่อน IPO ลงทุนผ่าน semiconductor supply chain (STM) ได้ หลัง IPO วันที่ 12 มิถุนายน SPCX จะเป็น expression ที่ชัดเจนที่สุด
`
  },
  {
    tag: "Defense-Materials",
    title: "Defense & Advanced Materials: Atoms กำลังชนะ Bits",
    subtitle: "Capital กำลัง rotate จาก software ที่ถูก AI disrupt ไปสู่ physical scarcity ที่ prompt ทำไม่ได้",
    conviction: "MED",
    last_updated: "2026-05-25",
    summary: "ในปี 2026 นักลงทุนกำลังตั้งคำถามว่า \"software company ที่ดูแข็งแกร่ง จะยังมีรายได้อยู่ใน 5 ปีข้างหน้าไหม?\" คำถามนี้ไม่ได้หมายความว่า AI ได้ทำลาย business เหล่านั้นแล้ว แต่แค่ความน่าจะเป็นที่ AI จะทำลายมันก็พอที่จะ compress multiple ของหุ้น software ได้ นี่คือ **AI Disruption Discount**",
    tickers: ["SOLS", "MTRN"],
    content: `# Defense & Advanced Materials: Atoms กำลังชนะ Bits
*Capital กำลัง rotate จาก software ที่ถูก AI disrupt ไปสู่ physical scarcity ที่ prompt ทำไม่ได้*

**Warren's Conviction:** MED
**Last Updated:** 2026-05-25

---

## ภาพรวม — Trend นี้คืออะไร

ในปี 2026 นักลงทุนกำลังตั้งคำถามว่า "software company ที่ดูแข็งแกร่ง จะยังมีรายได้อยู่ใน 5 ปีข้างหน้าไหม?" คำถามนี้ไม่ได้หมายความว่า AI ได้ทำลาย business เหล่านั้นแล้ว แต่แค่ความน่าจะเป็นที่ AI จะทำลายมันก็พอที่จะ compress multiple ของหุ้น software ได้ นี่คือ **AI Disruption Discount**

ในทางกลับกัน บริษัทที่มี physical scarcity moat — regulatory, geological, หรือ process-based — ไม่สามารถถูก AI disrupt ได้ คุณไม่สามารถ prompt ให้ NRC ออกใบอนุญาตโรงงาน UF6 ใหม่ได้ คุณไม่สามารถ prompt ให้เกิด beryllium deposit ใหม่ขึ้นมาได้ คุณไม่สามารถ prompt ให้ Kroll process titanium smelter สร้างเสร็จเร็วขึ้นได้

สิ่งที่น่าสนใจคือ physical scarcity companies เหล่านี้กำลังได้ประโยชน์จาก 4 tailwinds พร้อมกัน:
1. **Electrification/Grid Buildout**: transmission infrastructure, transformer capacity, nuclear baseload
2. **Global Defense Upcycle**: NATO เพิ่ม GDP% เป้าหมาย, Ukraine war normalize defense spending
3. **AI Datacenter Construction**: physical buildout ต้องการ steel, copper, titanium, advanced electronics
4. **Aerospace Recovery**: Boeing/Airbus ramp + SpaceX/satellite constellation buildout

และทั้งหมดนี้อยู่ที่ **cyclical trough valuation** — ราคาถูกที่สุดในรอบหลายปี เพราะตลาดยังมอง business models เหล่านี้ผ่านแว่น commodity cycle ไม่ใช่ structural scarcity

## หุ้นที่ได้ประโยชน์

**[[SOLS]]** (Solstice Advanced Materials) — โรงงาน UF6 conversion เดียวในสหรัฐฯ (Metropolis Works, Illinois) UF6 คือขั้นตอนบังคับในห่วงโซ่เชื้อเพลิงนิวเคลียร์ระหว่าง uranium mining และ enrichment ไม่มีทางข้ามได้

ทำไมถึง undervalued: สัญญา legacy ที่ $20/kgU กำลัง reprice ไปที่ $60+/kgU (ขึ้น 3x+) การ reprice นี้เป็น 100% flow-through ไปที่ EBIT โดยไม่ต้องลงทุน capex เพิ่ม Pro forma EBIT: $125M วันนี้ → **$673M ปี 2028** (ขึ้น 5.4x จาก contract repricing เพียงอย่างเดียว) แม้ให้ multiple ของ commodity chemicals (12-15x) ก็ได้ market cap $8-10B เทียบกับราคาปัจจุบันที่ต่ำกว่ามาก

**[[MTRN]]** (Materion Corporation) — ควบคุม 70%+ ของการผลิต beryllium โลก Beryllium ไม่มีสิ่งทดแทนในงานที่ต้องการ stiffness-to-weight ratio สูงและ thermal conductivity สูงพร้อมกัน (defense electronics, semiconductor tooling, space structures)

ตัวเร่ง demand ที่มาพร้อมกัน: defense bookings +40%, supply agreement กับ Commonwealth Fusion Systems สำหรับ SPARC fusion reactor (demand ใหม่ที่ไม่เคยมีมาก่อน), semiconductor fab tooling, satellite constellation buildout

**[[5726.JP]]** และ **[[5727.JP]]** (Osaka Titanium + Toho Titanium) — สองบริษัทญี่ปุ่นควบคุม ~80% ของ global titanium sponge production รัสเซียเคยเป็น ~40% ของ supply ให้ตะวันตก แต่หลัง Ukraine war การพึ่งพาถูกตัดเป็นโครงสร้าง (structural shift ไม่ใช่ temporary)

Kroll process ที่ใช้ผลิต titanium sponge: เป็นกระบวนการแบบ batch ปี 1950 ต้องใช้เวลา 5-7 ปีในการสร้าง capacity ใหม่ ราคา: ทั้งสองบริษัทซื้อขายที่ single-digit forward EBITDA multiples ณ cyclical trough

## ทำไมถึงน่าสนใจตอนนี้

การหมุนจาก bits ไป atoms ไม่ใช่ macro call หรือ tactical trade — มันเป็น structural trend ที่เกิดจาก AI Disruption Discount ที่กำลัง systematically compress multiple ของ software และ digital businesses ในขณะที่ physical moats ยังไม่ได้รับ premium ที่สมควร

**SOLS** เป็น highest-conviction idea: regulatory monopoly + pure pass-through economics + repricing ที่ locked in contractually แล้ว เป็น time-stamped catalyst ไม่ใช่ speculation

## มุมมองระยะยาว

Atoms vs Bits เป็น cross-cutting framework ที่มีผลต่อทุก sector ไม่ใช่แค่ materials SOLS, MTRN, และ Japanese titanium duopoly ทั้ง 4 ตัว อยู่นอก Warren's current watchlist และต้องการ dedicated research ก่อน position sizing แต่ thesis มีความ compelling สูงในฐานะ portfolio diversification จาก AI infrastructure names ที่ concentration risk สูง
`
  },
  {
    tag: "Digital-Advertising",
    title: "Digital Advertising ยุค AI: เมื่อโฆษณาฉลาดขึ้น ทุกคนได้ประโยชน์ยกเว้นคนที่ล้าหลัง",
    subtitle: "META และ GOOGL ถูกมองว่าเป็น \"AI laggard\" แต่นั่นคือโอกาสที่นักลงทุนส่วนใหญ่พลาดไป",
    conviction: "MED",
    last_updated: "2026-05-16",
    summary: "ในช่วงปี 2023-2024 narrative ที่ครอบงำ Wall Street คือ \"AI จะทำลาย Google Search\" เพราะถ้าคนหันไปถาม ChatGPT แทน Google ก็ไม่มีคนคลิก ad แล้ว narrative นี้ทำให้หุ้น META และ GOOGL ถูก discount ว่าเป็น \"AI loser\" ในขณะที่ MSFT ได้รับ premium จากการลงทุนใน OpenAI",
    tickers: ["META", "GOOGL"],
    content: `# Digital Advertising ยุค AI: เมื่อโฆษณาฉลาดขึ้น ทุกคนได้ประโยชน์ยกเว้นคนที่ล้าหลัง
*META และ GOOGL ถูกมองว่าเป็น "AI laggard" แต่นั่นคือโอกาสที่นักลงทุนส่วนใหญ่พลาดไป*

**Warren's Conviction:** MED
**Last Updated:** 2026-05-16

---

## ภาพรวม — Trend นี้คืออะไร

ในช่วงปี 2023-2024 narrative ที่ครอบงำ Wall Street คือ "AI จะทำลาย Google Search" เพราะถ้าคนหันไปถาม ChatGPT แทน Google ก็ไม่มีคนคลิก ad แล้ว narrative นี้ทำให้หุ้น META และ GOOGL ถูก discount ว่าเป็น "AI loser" ในขณะที่ MSFT ได้รับ premium จากการลงทุนใน OpenAI

แต่ความเป็นจริงในปี 2026 แตกต่างออกไป AI ไม่ได้ทำลายธุรกิจโฆษณาของ META และ GOOGL แต่กำลังทำให้มันดีขึ้น

ลองคิดดูว่า ad targeting ทำงานอย่างไร ในอดีต ระบบต้องเดาว่าคนที่กำลังอ่านบทความเรื่องการท่องเที่ยวอาจสนใจโรงแรม ตอนนี้ด้วย AI ที่เข้าใจ intent ได้ลึกกว่า ระบบรู้ว่าคนคนนี้กำลังวางแผนไปเชียงใหม่ในเดือนหน้า งบ 3,000 บาทต่อคืน และชอบโรงแรมที่มีสระว่ายน้ำ ความแม่นยำที่สูงขึ้นแปลตรงๆ ว่า advertiser ยินดีจ่ายมากขึ้นต่อ click เพราะ conversion rate สูงขึ้น

## ทำไมถึงน่าสนใจตอนนี้

ข้อมูลจาก agency checks ล่าสุดในปี 2026 แสดงว่า TikTok ad budgets โตขึ้น แต่ META และ YouTube ไม่ได้เห็น cannibalization ที่ market กลัว ผู้แพ้ที่ชัดเจนคือ Snapchat ซึ่ง absorb ส่วนแบ่งตลาดที่หายไปแทน ซึ่งหมายความว่า market ที่กังวลว่า TikTok จะ take share จาก META กำลังเข้าใจผิดอย่างมีนัยสำคัญ

Google AI Overview (ต่อมาเปลี่ยนชื่อเป็น AI Mode) ที่ generate summary ของ search results ด้วย AI นั้น ฟังดูเหมือนจะลด ad clicks เพราะคนไม่ต้อง scroll ผ่าน results อีกต่อไป แต่ในความเป็นจริง AI เข้าใจ intent ของ query ที่ complex และ long-tail ได้ดีขึ้นมาก ทำให้ GOOGL สามารถ monetize query ที่ก่อนหน้านี้ monetize ได้ยากกว่า ขยาย addressable inventory ออกไป ไม่ใช่ลดลง

Gemini Enterprise paid MAUs เพิ่ม +40% QoQ ซึ่งแสดงว่า enterprise adoption ของ Google AI tools กำลัง ramp ขึ้นและจะสร้าง recurring revenue stream ใหม่นอกเหนือจาก Search

META open-source Llama ecosystem ทำให้นักพัฒนาทั่วโลก build AI applications บน Meta infrastructure โดยตรง สร้าง flywheel ที่ data และ user engagement กลับเข้ามายัง Meta platform ทำให้ AI targeting model ของ Meta ดีขึ้นต่อเนื่อง

## หุ้นที่ได้ประโยชน์

**[[META]]** คือชื่อที่มี conviction สูงที่สุดใน Digital Advertising trend AI-enhanced ad targeting เพิ่ม ROI ให้ผู้โฆษณาโดยตรง ซึ่งทำให้พวกเขาเพิ่ม budget บน META platform Llama open-source ecosystem สร้าง developer moat ที่แยกจาก advertising business ให้ศักยภาพ upside เพิ่มเติม Instagram และ Facebook ยังคง engagement ที่แข็งแกร่งท่ามกลางการแข่งขันจาก TikTok ที่ intense กว่าที่เคย

**[[GOOGL]]** ได้ประโยชน์จาก AI Overview ad coverage expansion ที่ขยาย monetization ของ complex queries ออกไป YouTube ยังคงเป็น platform หลักสำหรับ video advertising ที่ไม่มีคู่แข่งที่ใกล้เคียงในฝั่งตะวันตก Gemini Enterprise monetization เป็น revenue stream ใหม่ที่กำลัง ramp ขึ้น

## หุ้นที่อาจเสียประโยชน์หรือเผชิญความเสี่ยง

**Snapchat** เป็นผู้แพ้ที่ชัดเจนที่สุดใน digital advertising landscape ปัจจุบัน เมื่อ TikTok ขยาย ad budget ก็มาจาก Snapchat ไม่ใช่จาก META หรือ YouTube ซึ่งสะท้อนว่า Snapchat ไม่มี differentiation ที่แข็งแกร่งพอในยุค AI

**Traditional media และ print advertising** เผชิญกับการเร่งตัวของ shift ไปสู่ digital เพราะ AI-enhanced digital advertising มี ROI ที่ดีกว่า traditional ออกไปอีก ทำให้ budget migration จาก traditional ไป digital เร็วขึ้น

บริษัท ad-tech ที่ทำงาน middle layer ระหว่าง advertiser และ publisher โดยไม่มี proprietary data เผชิญกับ compression ของ take rate เพราะ META และ GOOGL ทำ targeting เองได้ดีขึ้นโดยไม่ต้องพึ่ง third-party

## มุมมองระยะยาว

Digital advertising ใน AI era มีโครงสร้างที่ง่ายและดีมาก: META และ GOOGL มี distribution ที่ใหญ่ที่สุด ข้อมูลผู้ใช้ที่มากที่สุด และความสัมพันธ์กับ advertiser ที่ยาวนานที่สุด AI เพียงแค่ทำให้ assets เหล่านี้ generate return ได้มากขึ้นโดยไม่ต้องลงทุนใหม่มหาศาล

สิ่งที่จะ disrupt thesis นี้ได้คือ regulatory action ที่จำกัด AI-enhanced behavioral targeting หรือ antitrust action ที่กระทบ Google Search monopoly ทั้งสองความเสี่ยงมีอยู่แต่ยังไม่ถึงจุดที่จะ change thesis ในระยะสั้น

ใน 3-5 ปีข้างหน้า agentic AI จะเพิ่ม advertising dimension ใหม่: AI agents ที่ shopping และ making decisions แทนมนุษย์ META และ GOOGL ที่เข้าใจ human intent ดีที่สุดจะอยู่ในตำแหน่งที่ดีที่สุดในการ monetize decision layer นี้ด้วย
`
  },
  {
    tag: "Cyber-Security",
    title: "Cyber Security: เมื่อ AI ทั้งสร้างภัยและสร้างตลาดใหม่ให้ security",
    subtitle: "ทุก AI deployment ขยาย attack surface — และ AI กลายเป็น \"หมวดงบประมาณใหม่\" ภายในตัว security stack เอง",
    conviction: "MED",
    last_updated: "2026-06-05",
    summary: "ยุค AI ทำให้ cybersecurity ได้ประโยชน์เชิงโครงสร้างจาก 2 ทางพร้อมกัน",
    tickers: ["CRWD"],
    content: `# Cyber Security: เมื่อ AI ทั้งสร้างภัยและสร้างตลาดใหม่ให้ security

*ทุก AI deployment ขยาย attack surface — และ AI กลายเป็น "หมวดงบประมาณใหม่" ภายในตัว security stack เอง*

**Warren's Conviction:** MED
**Last Updated:** 2026-06-05

---

## ภาพรวม — Trend นี้คืออะไร

ยุค AI ทำให้ cybersecurity ได้ประโยชน์เชิงโครงสร้างจาก 2 ทางพร้อมกัน

**ทางแรก — AI สร้างภัยใหม่:** ทุกครั้งที่องค์กรเอา AI ไปใช้ มันขยายพื้นที่ที่ถูกโจมตีได้ (attack surface) — agentic workload แตะข้อมูลอ่อนไหว สั่งงานอัตโนมัติ และสร้าง identity ประเภทใหม่ที่เรียกว่า "non-human / agentic identity" (ตัวตนของ AI agent, bot, service account) ที่ต้องถูกป้องกัน

**ทางที่สอง — AI กลายเป็นหมวดงบใหม่ภายใน security เอง:** ตอนนี้มีหมวดใช้จ่ายใหม่เกิดขึ้นชัดเจน — AI security posture (การวาง guardrail ให้ AI), AI SOC agents (เอเจนต์ช่วยทีม security operations), GenAI data security (ป้องกันข้อมูลใน GenAI), และ agentic-identity security

คำถามการลงทุนจึงไม่ใช่ "demand จริงไหม" (จริงแน่นอน) แต่คือ **"ใครได้เงิน AI-security ก้อนใหม่นี้"** — ผู้เล่นเดิมที่เป็นเจ้าของแพลตฟอร์ม cloud/endpoint อยู่แล้ว (Microsoft, CrowdStrike, Palo Alto), specialist เฉพาะทาง, หรือ DIY (องค์กรเอา model ของ Anthropic/OpenAI ไปฝังในระบบ security ของตัวเอง)

## หุ้นที่ได้ประโยชน์

**[[CRWD]]** (CrowdStrike) — cloud-native security platform บน Falcon (33 modules, NRR 115%) จากผลสำรวจ IT executive ของ UBS Evidence Lab รอบล่าสุด CrowdStrike คือ **incumbent ที่มี momentum ด้าน AI-security ดีที่สุดในกลุ่มสามใหญ่** — เป็นรายเดียวในสามเจ้า (Microsoft / CrowdStrike / Palo Alto ที่ครอง mindshare 40%+) ที่ "ความตั้งใจจะใช้ในอนาคต" ยังเพิ่มขึ้น ส่วน Charlotte AI (SOC agent ของ CrowdStrike) เป็นแพลตฟอร์มอันดับ 2 ที่องค์กรนำไปใช้

จุดที่ต้องระวัง: ราคา CrowdStrike ยัง "assume perfection" ทุกไตรมาส (ซื้อขายราว 54x EV/FCF, PEG สูง) — ธุรกิจดีจริงแต่ราคาแพง พลาดไตรมาสเดียวก็ลงแรง และยังเจอแรงกดดันเชิงโครงสร้าง 2 ชั้น: (1) Microsoft bundling Defender ขายรวมราคาถูก/ฟรี, (2) DIY agentic SOC — องค์กรเริ่มฝัง model เองแทนซื้อ packaged solution

## ทำไมถึงน่าสนใจตอนนี้

มีพัฒนาการสำคัญที่ช่วยลดความเสี่ยงฝั่งลบของ thesis: บทวิจัยเดือนพฤษภาคม 2026 ชี้ว่า **Anthropic วาง Claude Security เป็น "ตัวเสริม ไม่ใช่ตัวแทน"** ของ runtime security ที่ผู้เล่นเดิมทำอยู่ — Anthropic ไม่รุกเข้ามาทำ production/runtime detection แข่ง และยังขยาย Compliance API เชื่อมกับ 28 เครื่องมือ cyber เพื่อให้ทีม security จัดการ AI ได้ง่ายขึ้น

นี่หมายความว่าความกลัวที่ว่า "AI labs จะกินงาน security เอง" นั้นเกินจริงในระยะนี้ — ผู้เล่นเดิมที่ฝังลึกในระบบลูกค้ายังมี moat อยู่ แม้บางส่วนของ cloud-security posture (เช่นการสแกน infrastructure-as-code) อาจถูก commoditize ไปบ้าง

## มุมมองระยะยาว

Cybersecurity ในยุค AI เป็น secular trend ที่แท้จริง แต่ในกรอบ watchlist ปัจจุบันมีตัวแทนเพียงตัวเดียวคือ CrowdStrike ทำให้ยังเทียบคู่แข่งแบบ head-to-head ไม่ได้เต็มที่ (Palo Alto, Zscaler, SentinelOne, Okta, CyberArk ยังไม่อยู่ใน watchlist)

วินัยของ Warren คือเก็บ CrowdStrike เป็น **WATCH** — ธุรกิจคุณภาพดี posture leader แต่ราคายังแพง รอจังหวะที่ margin of safety เปิดก่อน ไม่ไล่ราคา Conviction = MED และจะยกระดับขึ้นได้เมื่อ (ก) มีหุ้น cyber ตัวที่ 2 เข้า watchlist ให้เทียบกันได้ หรือ (ข) ราคา CrowdStrike เปิดช่องเข้าซื้อชัดเจน

สัญญาณสำคัญที่ต้องเฝ้าดู: DIY / agentic-SOC จะแย่งส่วนแบ่งจาก packaged AI-SOC platform ต่อเนื่องในผลสำรวจ 2-3 รอบถัดไปหรือไม่
`
  }
];