#!/usr/bin/env python3
"""
generate_theme.py
Parses Warren's Theme Playbooks (Markdown, YAML frontmatter + sections)
and generates theme.js for the oat-investor website.

Usage: python3 scripts/generate_theme.py
"""

import json
import os
import re
from datetime import date
from pathlib import Path

ROOT   = Path(__file__).parent.parent
OAT_OS = ROOT.parent

THEMES_DIR = os.environ.get(
    "THEMES_DIR",
    str(OAT_OS / "oat-investment-knowledge" / "Research" / "warren" / "themes"),
)
OUTPUT_FILE = os.environ.get("OUTPUT_FILE", str(ROOT / "theme.js"))
WATCHLIST_FILE = os.environ.get(
    "WATCHLIST_FILE",
    str(OAT_OS / "kim-line-bot" / "config" / "watchlist.json"),
)

DISPLAY_ORDER = [
    "AI-Revolution",
]


def load_watchlist_tickers():
    try:
        with open(WATCHLIST_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        return {s["symbol"] for s in data.get("stocks", [])}
    except Exception:
        return set()


def linkify_ticker_cells(content, tickers):
    """Wrap plain-ticker first-cells in markdown tables as **[[TICKER]]** so the
    client-side renderer turns them into ticker pills, matching trends.js convention."""
    out_lines = []
    for line in content.splitlines():
        m = re.match(r"^(\|\s*)([A-Z]{1,6})(\s*\|)(.*)$", line)
        if m and m.group(2) in tickers:
            line = f"{m.group(1)}**[[{m.group(2)}]]**{m.group(3)}{m.group(4)}"
        out_lines.append(line)
    return "\n".join(out_lines)


def parse_frontmatter(content):
    """Parse the simple YAML frontmatter block between --- markers."""
    fm = {}
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", content, re.DOTALL)
    if not m:
        return fm, content
    fm_block, body = m.group(1), m.group(2)
    for line in fm_block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            items = [v.strip() for v in value[1:-1].split(",") if v.strip()]
            fm[key] = items
        else:
            fm[key] = value
    return fm, body


def parse_theme_file(filepath, tickers):
    tag = os.path.splitext(os.path.basename(filepath))[0]

    with open(filepath, "r", encoding="utf-8") as f:
        raw = f.read()

    frontmatter, body = parse_frontmatter(raw)
    body = linkify_ticker_cells(body, tickers)

    # tickers appearing as first column of the TQR table (## 4.) — ordered, deduped
    theme_tickers = []
    seen = set()
    for t in re.findall(r"\*\*\[\[([A-Z]{1,6})\]\]\*\*", body):
        if t not in seen:
            seen.add(t)
            theme_tickers.append(t)

    return {
        "tag": tag,
        "title": frontmatter.get("theme", tag),
        "conviction": frontmatter.get("conviction", ""),
        "stage": frontmatter.get("stage", ""),
        "last_review": frontmatter.get("last_review", ""),
        "next_review_due": frontmatter.get("next_review_due", ""),
        "kpi_breach_count": frontmatter.get("kpi_breach_count", ""),
        "sub_trends": frontmatter.get("sub_trends", []),
        "tickers": theme_tickers,
        "content": body,
    }


def escape_for_js_template_literal(text):
    text = text.replace("\\", "\\\\")
    text = text.replace("`", "\\`")
    text = text.replace("${", "\\${")
    return text


def js_string(value):
    value = str(value)
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("\n", "\\n")
    return f'"{value}"'


def generate_theme_js(themes):
    today = date.today().isoformat()
    lines = []
    lines.append("// Auto-generated by generate_theme.py — do not edit manually")
    lines.append(f"// Last generated: {today}")
    lines.append("var THEMES_DATA = [")

    for i, t in enumerate(themes):
        escaped_content = escape_for_js_template_literal(t["content"])
        tickers_js = "[" + ", ".join(f'"{x}"' for x in t["tickers"]) + "]"
        sub_trends_js = "[" + ", ".join(f'"{x}"' for x in t["sub_trends"]) + "]"

        lines.append("  {")
        lines.append(f'    tag: {js_string(t["tag"])},')
        lines.append(f'    title: {js_string(t["title"])},')
        lines.append(f'    conviction: {js_string(t["conviction"])},')
        lines.append(f'    stage: {js_string(t["stage"])},')
        lines.append(f'    last_review: {js_string(t["last_review"])},')
        lines.append(f'    next_review_due: {js_string(t["next_review_due"])},')
        lines.append(f'    kpi_breach_count: {js_string(t["kpi_breach_count"])},')
        lines.append(f"    sub_trends: {sub_trends_js},")
        lines.append(f"    tickers: {tickers_js},")
        lines.append(f"    content: `{escaped_content}`")
        comma = "," if i < len(themes) - 1 else ""
        lines.append(f"  }}{comma}")

    lines.append("];")
    return "\n".join(lines)


def main():
    print("🎯 generate_theme.py\n")
    tickers = load_watchlist_tickers()
    themes = []
    missing = []

    for tag in DISPLAY_ORDER:
        filepath = os.path.join(THEMES_DIR, f"{tag}.md")
        if not os.path.exists(filepath):
            missing.append(tag)
            print(f"  WARNING: {filepath} not found, skipping.")
            continue
        theme = parse_theme_file(filepath, tickers)
        themes.append(theme)
        print(f"  Parsed: {tag} — stage={theme['stage']}, conviction={theme['conviction']}, tickers={theme['tickers']}")

    if missing:
        print(f"\nWARNING: {len(missing)} file(s) missing: {missing}")

    js_output = generate_theme_js(themes)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_output)

    print(f"\nDone. {len(themes)} theme(s) written to:\n  {OUTPUT_FILE}")
    print(f"File size: {os.path.getsize(OUTPUT_FILE):,} bytes")


if __name__ == "__main__":
    main()
